### ISSUE TITLE
[BUG]: Power BI template times out on Audit Log table

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#1021]
Hi there,

When attempting to open Dashboard-PowerPlatformAdminDashboard-2021-04-08.pbit, the data load consistently fails.  It's timing out loading the Audit Log (admin_auditlog) table.

I happened to notice that the "connector" used in the newer report is the Dataverse one while previous reports used the Common Data Service (Legacy) one.

When I load up that table using CDS, it works.  If I then try to load up that table using Dataverse, it times out.  

So I created a support ticket.  According to the engineer, the Dataverse Connector in Power BI utilizes TDS to connect to the Dataverse and Audit Log is in a list of tables that do not load using TDS.

I believe this is slightly different than issue #967 since I'm getting a timeout instead of an ODBC error, but wanted to double check here.
Thank you!

**Comment by manuelap-msft** [comment]
Due to limitations with the TDS endpoint used for DirectQuery when used with Dataverse (see https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#limitations), only tables of a specific size can be retrieved and likely your Audit Log table is larger than that.

Like mentioned in #967, we are going to have to offer two dashboards going forward - Import mode for larger tenants, DirectQuery for smaller tenants. Because of the limitations, DirectQuery will not work for larger tenants unfortunately. We are still working on preparing the two dashboards.

Thank you for using the CoE
Manuela

**Comment by manuelap-msft** [comment]
Here is a version of the dashboard using Import instead of DirectQuery that you can use in the meantime: https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit

**Comment by osbornecc** [comment]
Thank you, that dashboard loaded up great!
