### ISSUE TITLE
[BUG]: Center of Excellence (CoE) 3. Turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted) dont work

### ISSUE THREAD

**Issue by Maxiiii-s** [microsoft/powerapps-tools#1073]
Hello community,

I am in the process of setting up the Centre of Excellence. However, I am failing at point 3 "Turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted)"

The flow could not be activated: CLEANUP - Admin | Sync Template v3 (Check Deleted). Error: Error saving the flow. Code: InvalidPaginationPolicy, message: 'The pagination policy of the workflow execution action "Get_Environments" of type "OpenApiConnection" in row 1 and column 26222 is invalid. The value specified for the property "minimumItemsCount" exceeds the maximum value allowed. Actual value: 100000. Maximum value: 5000.".

What can I do now?

Have I done something wrong?

Thank you very much for your response in advance.

Many greetings

Max

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on: 
https://github.com/microsoft/coe-starter-kit/issues 

**For this particular issue, you have hit the pagination limit.** 
All the flows have this pagination policy. It indicates that you are using an insufficient or trial license. 
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes. 

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles) 

And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits) 

And hence our requirements for licenses as described in our [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).
