### ISSUE TITLE
[BUG]: Missing data in sharepoint lists after running flow

### ISSUE THREAD

**Issue by bhaub78** [microsoft/powerapps-tools#114]
**Describe the bug**
The latest published flow for publishing sharepoint lists doesn't include the admin config data required in CI_configAdminSetup to populate the drop down for Notification Method.

**To Reproduce**
1. Run SP List flow
2. Go to admin app
3. Click Admin Settings
4. Click Notification Method drop down
5.  You'll see it just says "Find Items" as the required data in SP isn't there.

**Expected behavior**
SP list flow should load all the data like it used ot

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mr-dang-msft** [comment]
Hi @bhaub78,
The flow in question has not been changed since the first version. If you have deployed the lists already, you would not repeat this step again if updating. We have not changed the column structure of any lists.

Another user has experienced this. If you are re-importing the Admin app or importing it for the first time, it will have existing SharePoint connections in it. You will need to remove these again and add your own. 

Once that is done, you will need to save and republish the app in order for it to run with the correct connection and show options.

For reference: https://github.com/MicrosoftDocs/powerapps-docs/issues/1139#issuecomment-599032508
