### ISSUE TITLE
[BUG]: Sync Template errors against default environment

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#156]
**Describe the bug**
We've configured our CoE to send daily email notifications when errors occur with the default sync v2 templates we've imported as part of the core solition. We receive an email each day saying 3 sync templates have issues running against our default environment.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 -  Flow [Sync Template v2 (Custom Connectors), Sync Template v2 (Flows and Sync Template v2 (Model Driven Apps]

**To Reproduce**
The error occurs for the above flows each evening just after midnight.

**Expected behavior**
We want the flows to run correctly against the default environment.

**Screenshots**
Happy to provide detailed screenshots to whoevers picks up this issue.

**Additional context**
We initially thought this issue was related to permissions. We have our flows running using a service account and we attempted to reset the connection to the service account for the section of the flow that's failing. This hasn't resolved the issue, it appears there's something within our default environment that's tripping up the flow. The same flow runs correctly for a number of other environments we have.

**Comment by manuelap-msft** [comment]
Would you be able to share a screenshot of where the Flow has failed with the action that is failing and it's error details? Thank you!

**Comment by audrieMSFT** [comment]
I am happy to offer help. Seeing a screen shot of the run page where the error stops the flow (see red checks) would help.

**Comment by melmgcoe** [comment]
Hello Manuela, Audrie

Thanks for your offer to help. I've attached a screenshot of the error for each flow that fails.

Let me know if you need anything else.

Regards,

Mel

[Admin Sync Flow errors.docx](https://github.com/microsoft/powerapps-tools/files/4368960/Admin.Sync.Flow.errors.docx)

**Comment by manuelap-msft** [comment]
Thank you for providing those details! For the first two errors (Custom Connectors and Model Driven Apps) it looks like you have resources by makers that have since left the organisation (orphaned or abandoned resources) - we have implemented error handling for those scenarios, can you please confirm you have the latest version of the solution installed?

If you open the Admin | Sync Template v2 (Custom Connectors) and open up the "Get Custom Connectors and store them in CoE CDS Entity" scope (in the same way you have done when you had to update the connection references), the Get User Profile should look like the below with two branches underneath it, one for abandoned apps.
![image](https://user-images.githubusercontent.com/55705669/77312571-26fd9c00-6cfa-11ea-9860-180afcf6a309.png)

If you open the Admin | Sync Template v2 (Model Driven Apps) and open up the "Get Model Driven Apps and store in CoE CDS Entity" scope (in the same way you have done when you had to update the connection references), the Get User Profile should look like the below with two branches underneath it, one for abandoned apps.
![image](https://user-images.githubusercontent.com/55705669/77312668-54e2e080-6cfa-11ea-9094-08191d946fa1.png)

If your Flows do not look like this, please upgrade to the latest version of the Core Components by downloading this file here https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_32_managed.zip and upgrading your solution by 
1. Navigate to make.powerapps.com
2. Import Solution
3. Select the newly downloaded solution
4. Select "Upgrade" and "Overwrite customizations" during import options
5. Configure the Flow connections

For the Admin | Sync Template v2 (Flows) flow it looks like you are getting throttled, you can increase the Retry policy and reduce concurrency in Foreach loops to reduce simultaneous calls . Please do this after upgrading the solution by 

1. Open Admin | Sync Template v2 (Flows) to Edit
2. Expand the step: Get Flows and store them in CoE CDS Entity
3. Expand the step: Check if Environment is deleted
4. Expand the step: Apply to each Flow
5. Go to settings for the Get Flow as Admin call by clicking on ... and selecting Settings
6. Change the Retry Policy
![image](https://user-images.githubusercontent.com/55705669/77313353-9c1da100-6cfb-11ea-8901-03d533039344.png)

If this doesn't help, you can also Reduce concurrency in Foreach loops to reduce simultaneous calls 

1. Open Admin | Sync Template v2 (Flows) to Edit
2. Expand the step: Get Flows and store them in CoE CDS Entity
3. Expand the step: Check if Environment is deleted
4. Go to Settings for Apply to each Flow
5. Reduce the degree of parallelism here. The Default is 50 and you can reduce the number down to see what works for you. Note: this will mean your Flow will take longer to complete.
![image](https://user-images.githubusercontent.com/55705669/77313436-c7a08b80-6cfb-11ea-8928-12b6ea1a40c8.png)

**Comment by manuelap-msft** [comment]
(Sorry I accidentally closed this now. Please try the above steps and let me know if that works or if you experience any further issues)

**Comment by melmgcoe** [comment]
Hi Manuela,

Thanks for the info.

Let me review your suggestions and come back to you with an update shortly.

Regards,

[cid:image007.png@01D60121.644B66E0]
[M&G Plc Logo]
[cid:image008.png@01D60121.644B66E0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D60121.644B66E0]


[cid:image009.png@01D60121.644B66E0]
[cid:image009.png@01D60121.644B66E0]
[cid:image011.png@01D60121.644B66E0]

**Comment by melmgcoe** [comment]
Hi Manuela,

We're running v1.20 for the core components.

I'll go ahead and install the latest version as advised but wanted to call out the fact that the error handling you mentioned below exists for the Custom Connectors flow but not the Model Driven Apps flow:

Custom connectors flow

[cid:image001.jpg@01D601EA.F46A71C0]

Model Driven flow

[cid:image002.jpg@01D601EA.F46A71C0]

Is there anyway to send myself and a colleague an email notification whenever there's a new version of the CoE to download? This would be useful and would avoid us needing to manually check GitHub for the latest version.

Re the Sync Template v2 (Flows) flow, I've updated the retry attribute based on your first suggestion and will let you know what happens tomorrow. Assuming this doesn't work, I'll also try your second suggestion as advised.

Regards,

[cid:image004.png@01D601EA.F46A71C0]
[M&G Plc Logo]
[cid:image005.png@01D601EA.F46A71C0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image006.png@01D601EA.F46A71C0]


[cid:image006.png@01D601EA.F46A71C0]
[cid:image006.png@01D601EA.F46A71C0]
[cid:image009.png@01D601EA.F46A71C0]

**Comment by melmgcoe** [comment]
Hi Manuela,

Just to follow on Mel's email I am part of the Biz App Customer Advisory Board, so if there is a notification of new releases through that channel please let us know - I simply may not be aware of it!

Thanks,

Nick



M&G plc - Restricted
From: Uy, Melvin <melvin.uy@uk.pgds.com>
Sent: 24 March 2020 14:46
To: microsoft/powerapps-tools <reply@reply.github.com>; microsoft/powerapps-tools <powerapps-tools@noreply.github.com>
Cc: Author <author@noreply.github.com>; Power Platform CoE <PowerPlatformCoE@MandG.co.uk>
Subject: RE: [microsoft/powerapps-tools] [BUG]: Sync Template errors against default environment (#156)

Hi Manuela,

We're running v1.20 for the core components.

I'll go ahead and install the latest version as advised but wanted to call out the fact that the error handling you mentioned below exists for the Custom Connectors flow but not the Model Driven Apps flow:

Custom connectors flow

[cid:image002.jpg@01D601EB.91DFBD70]

Model Driven flow

[cid:image003.jpg@01D601EB.91DFBD70]

Is there anyway to send myself and a colleague an email notification whenever there's a new version of the CoE to download? This would be useful and would avoid us needing to manually check GitHub for the latest version.

Re the Sync Template v2 (Flows) flow, I've updated the retry attribute based on your first suggestion and will let you know what happens tomorrow. Assuming this doesn't work, I'll also try your second suggestion as advised.

Regards,

[cid:image004.png@01D601EB.91DFBD70]
[M&G Plc Logo]
[cid:image005.png@01D601EB.91DFBD70]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image006.png@01D601EB.91DFBD70]


[cid:image006.png@01D601EB.91DFBD70]
[cid:image006.png@01D601EB.91DFBD70]
[cid:image009.png@01D601EB.91DFBD70]

**Comment by manuelap-msft** [comment]
Thank you, we are currently on version 1.32 of the Core Components and have definitely included some bug fixes here so would recommend an upgrade.

You will still have to manually reduce concurrency in Foreach loops to reduce simultaneous calls after the upgrade as this is not part of the solution yet. 

At the moment, we don't have a good way for you to subscribe to updates to the kit but we are looking at a few different options for this now.

**Comment by melmgcoe** [comment]
Thanks for the additional info. Please keep me in the loop once you've made a decision re update notifications.

Regards,

[cid:image007.png@01D601F5.04E5E980]
[M&G Plc Logo]
[cid:image008.png@01D601F5.04E5E980]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D601F5.04E5E980]


[cid:image009.png@01D601F5.04E5E980]
[cid:image009.png@01D601F5.04E5E980]
[cid:image011.png@01D601F5.04E5E980]

**Comment by melmgcoe** [comment]
Hi Manuela,

I can confirm that all our flows have successfully run since upgrading the core components kit to v1.32.

Please go ahead and close the support ticket, appreciate your help.

Regards,

[cid:image007.png@01D60358.F5CB8710]
[M&G Plc Logo]
[cid:image008.png@01D60358.F5CB8710]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D60358.F5CB8710]


[cid:image009.png@01D60358.F5CB8710]
[cid:image009.png@01D60358.F5CB8710]
[cid:image011.png@01D60358.F5CB8710]

**Comment by manuelap-msft** [comment]
That's great, thank you for confirming!
