### ISSUE TITLE
[BUG]: Logo URL - key parameters under Admin Settings

### ISSUE THREAD

**Issue by Giorgosi** [microsoft/powerapps-tools#176]
I specified the url where the logo can be found under admin Settings/ "Logo URL"
When accessing the Crisis Communication app the logo isn't appearing. Any idea where how to resolve this? When accessing the url I see effectively the logo without any problem. Thanks

**Comment by mr-dang-msft** [comment]
Hi @Giorgosi ,
Part of the logo implementation has been in the app. The HomeComponent on the Home Screen has a Logo property which you can point to:
`varConfig.Logo`

This works well for desktop, though it is kind of large on the mobile form factor. We've not finished the responsive nature of this yet which is why it's not fully in.
