### ISSUE TITLE
[BUG]: Admin Sync Audit Log enablement issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#184]
**Describe the bug**
We're unable to turn on the newly introduced CoE Audit Logs. We need this new version working as our Office 365 tenant doesn't support basic authentication. The attached error appears which refers to an issue with the child workflow needing to be published.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [CoE Audit Logs]
 - Version [v1.0.0.7]
 - App or Flow [Admin | Sync Audit Log]

**To Reproduce**
1. Turn on the flow
2. See error

**Expected behavior**
The flow should turn on sucessfully.

**Screenshots**
See attached screenshot.

**Additional context**
N/A
![Capture - Audit log error](https://user-images.githubusercontent.com/62425530/77767114-7dd7de00-7038-11ea-9974-d82d74a1256f.JPG)

**Comment by manuelap-msft** [comment]
Have you configured and turned on the child flow that is part of the solution?

**Comment by melmgcoe** [comment]
Apologies Manuela, there's been confusion on my part.

The actual issue I should have called out relates to turning on the child workflow and not the parent workflow. The following error appears when I attempt to do this:

[cid:image001.jpg@01D60448.46DF15F0]

Does the error relate to a permissions issue with the API connector linked to the Audit log solution?

Regards,

[cid:image002.png@01D60448.46DF15F0]
[M&G Plc Logo]
[cid:image008.png@01D60448.46DF15F0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D60448.46DF15F0]


[cid:image009.png@01D60448.46DF15F0]
[cid:image009.png@01D60448.46DF15F0]
[cid:image011.png@01D60448.46DF15F0]

**Comment by manuelap-msft** [comment]
Sorry, the image didn't come through, can you try uploading that again? Thank you!

**Comment by melmgcoe** [comment]
NP, I've attached the JPG file to Github directly. Hopefully you get it this time round.

![Capture - Audit log error 2](https://user-images.githubusercontent.com/62425530/77769754-289dcb80-703c-11ea-8daa-78abde75ce7f.JPG)

**Comment by manuelap-msft** [comment]
Awesome, that helps! Basically that flow violates DLP Policies set up for that environment likely due to the custom connector it's using. We are actually just working through an issue here!
If you are using a dedicated environment for the CoE, I would recommend making the business data only group the default group of that environment and that should work. 
If you are not using a dedicated environment, that's not recommended and I'll update you on how to move the custom connector.

**Comment by melmgcoe** [comment]
Thanks Manuela, we have a dedicated environment for our CoE and a less restrictive data protection policy applied to it.

I’ve made the Business data group the default group for this policy and that worked a treat 😊 I’ll follow the rest of the documentation and confirm once all the steps have been actioned.

Are you able to keep my ticket on hold until then just in case we encounter any further issues?

@Power Platform CoE<mailto:PowerPlatformCoE@MandG.co.uk> – the issue with enabling the Child Admin audit sync flow did relate to our data protection policy as Paul implied. However, it was a case of ensuring the Business Data group is the default group for our less restrictive policy (instead of having to specifically add the API custom connector to the Business Data group like we thought previously). Hopefully Steve\Security don’t have any issues with this change, happy to call it out when he returns in April.

Regards,

[cid:image007.png@01D60454.6FB00960]
[M&G Plc Logo]
[cid:image008.png@01D60454.6FB00960]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D60454.6FB00960]


[cid:image009.png@01D60454.6FB00960]
[cid:image009.png@01D60454.6FB00960]
[cid:image011.png@01D60454.6FB00960]

**Comment by manuelap-msft** [comment]
Yes of course, we can keep this open!

Typically, we would advise to add the custom connector to the business data only group using PowerShell. We are just debugging an issue where, because the custom connector is part of a solution, this doesn't seem to work properly. I'll keep you updated here, once that is fixed so you can return to having your non business data allowed policy your default policy on that environment

**Comment by Daleyon** [comment]
@manuelap-msft @melmgcoe thank you for this! I ran into the same error moments ago:
 "{"error":{"code":"ApiPolicyOrThrottlingViolation","message":"Flow '' cannot be activated due to either admin API policies or billing throttling. "}}.

**Comment by amweise** [comment]
Hi, seeing the same issue.  Changed the DLP default group and no success.

**Comment by melmgcoe** [comment]
Hi Manuela,

I'm pleased to report that I've finished working through the process doc - both the child and parent workflows are enabled and running without issue.

We now have a CoE environment that's running v1.32 and a custom connector setup to access the O365 Audit Logs using a bearer token.

Taking this account, can you confirm that I no longer need to import the zip file entitled Flow-SyncAuditLogs.zip included as part of the starter kit for v1.32?

I did attempt to do this yesterday and encountered an error with setting up the connections.

Thinking about it again though, I don't believe it's required. The steps we followed to setup the bearer token method involved importing the audit logs as a separate solution within our CoE environment?

I'm hoping that I've understood this correctly so please let me know. Assuming so, we'll crack on and install the Audit and Report and Nurture components.

Regards,

[cid:image001.png@01D609D3.029336C0]
[M&G Plc Logo]
[cid:image008.png@01D609D3.029336C0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D609D3.029336C0]


[cid:image009.png@01D609D3.029336C0]
[cid:image009.png@01D609D3.029336C0]
[cid:image011.png@01D609D3.029336C0]

**Comment by manuelap-msft** [comment]
Yes, that's absolutely correct - the Flow-SyncAuditLogs.zip contains the flow that's using basic authentication to connect to the audit log. Seeing as you set up the one with the Azure AD registration intended to be used for accounts with MFA, this .zip won't be needed!

**Comment by melmgcoe** [comment]
That’s great, thanks for the confirmation 😊 Please go ahead and close the ticket for this issue.

Regards,

[cid:image001.png@01D609DA.18785C70]
[M&G Plc Logo]
[cid:image008.png@01D609DA.18785C70]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D609DA.18785C70]


[cid:image009.png@01D609DA.18785C70]
[cid:image009.png@01D609DA.18785C70]
[cid:image011.png@01D609DA.18785C70]

**Comment by manuelap-msft** [comment]
Hello,

in order to add the custom connector to the business data only group of your DLP policy, please follow the following steps.

1. Follow the steps here to set up the PowerShell cmdlets, if not already done https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell
2. Open the DLP Policy you want to add the custom connector to, and note the GUID of the DLP Policy. You can also achieve this by calling Get-AdminDlpPolicy in PowerShell and noting the PolicyName
![image](https://user-images.githubusercontent.com/55705669/79856920-e6f70b00-83c4-11ea-8d05-9e2f899e9038.png)
3. Navigate to flow.microsoft.com > Data > Custom Connector and select Edit on the custom connector
![image](https://user-images.githubusercontent.com/55705669/79857215-5a991800-83c5-11ea-8195-6412ed8af18d.png)
4. Note the Connector Name (everything between custom and edit)
![image](https://user-images.githubusercontent.com/55705669/79857284-72709c00-83c5-11ea-99d9-2bcc27626372.png)
5. In PowerShell, use Add-CustomConnectorToPolicy to add the custom connector to your policy.

The format here is:
Add-CustomConnectorToPolicy -PolicyName {your policy name GUID} -ConnectorName {the nName you copied from above} -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/{your environment GUID{/apis/{your connector name} 

for example this should look like this
Add-CustomConnectorToPolicy -PolicyName fbe6cc78-1234-1234-9362-a87c1618abcd -ConnectorName shared_admin-5foffice-20365-20management-20api-5f218397e7aabcdef -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/aab123ca-1234-1234-8b12-eae67cabcdef/apis/shared_admin-5foffice-20365-20management-20api-5f218397e7aabcdef

**Comment by melmgcoe** [comment]
Hi Manuela,

Thanks for letting me know about the bug fix.

I've managed to get the API connector added to our Business Data Only group and subsequently reverted the default group to No Business Data Allowed.

Regards,

[cid:image007.png@01D61A51.34DBEDF0]
[M&G Plc Logo]
[cid:image008.png@01D61A51.34DBEDF0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D61A51.34DBEDF0]


[cid:image009.png@01D61A51.34DBEDF0]
[cid:image009.png@01D61A51.34DBEDF0]
[cid:image011.png@01D61A51.34DBEDF0]
