### ISSUE TITLE
[BUG]: Developer Compliance Center Links Hard Coded for Commercial Endpoint

### ISSUE THREAD

**Issue by tetaylor-msft** [microsoft/powerapps-tools#250]
**Describe the bug**
When reviewing an app in the Developer Compliance Center the links to App Settings, Re-Publish, and launch are using a hard coded commercial endpoint (make.powerapps.com).  When the toolkit is used on U.S. Government Cloud the links are broken. 

**Component (please tell us which flow or app you are experiencing issues with):**
- Developer Compliance Center App

**To Reproduce**
1. Deploy the toolkit in GCC
2. View an App in Developer Compliance Center
3. Click the App Settings Link

**Expected behavior**
Should navigate to the app (Requires an environment variable to collect the desired Maker Portal URL)

**Comment by JeneferM-MSFT** [comment]
Thank you for reporting this issue, we have added it as a to-do item in our backlog.

**Comment by JeneferM-MSFT** [comment]
Hi. We have a local fix for your issue. Thanks again for reporting and making CoE great! 

Can you confirm the following for me so that we have a good fix? 
Are the following the correct URI's for you?

For the Power Apps Maker experience:
- https://make.gov.powerapps.us (if you are GCC)
- https://make.high.powerapps.us (if you are GCC High)

For the Power Apps Player experience:
- https://apps.gov.powerapps.us (if you are GCC)
- https://apps.high.gov.powerapps.us (if you are GCC High)

**Comment by JeneferM-MSFT** [comment]
chatted offline and confirmed all but this one: https://apps.high.gov.powerapps.us (if you are GCC High)
Will release the fix with the next shipment of CoE.

**Comment by JeneferM-MSFT** [comment]
Hello. This has been resolved in the newest version of the CoE kit. 
Please note that we have a new field in the CoE Settings which determines the behavior. It defaults to Commencial tenants but you can update it to your tenant type. 
See the **_Tenant Type_** field in the set up documentation: [Configure the CoE Settings Entity](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-the-coe-settings-entity).

Thanks for helping to make CoE great!
