### ISSUE TITLE
[BUG]: Compliance Detail Request Flow Notification

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/powerapps-tools#267]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Compliance and Report Component
 - Version [e.g. 1.29]
 - Flow- Compliance Detail Request

**Bug**

I have multiple apps for which I never received any email related to Compliance Detail Request . When I shared the App with a security group, then I was notified ; which is an expected behavior . Our concern is , when we create an app for the first time ; we expect the business justification email to be send at that time itself along with Welcome Email or separately so that user fill the details at that time itself .  This notification is triggered only when app is shared broadly or with a group which makes this flow of no use. What if users are creating multiple apps but not sharing it with a group or more than 20 users, in that case they will never get the notification for filling business justifications and hence they would never fill the details . Second , it is almost impossible to give premium licenses to all users . Is there no other way to handle this ?

**Screenshots**

**Comment by manuelap-msft** [comment]
There is no "one size fits all" solution for a Center of Excellence (CoE). Some companies will want a very restrictive set of rules on their organization in hopes of mitigating the unknown, while others will want to let users personally explore without limitations. Because of this, the CoE Starter Kit doesn't come equipped with a set of design patterns for everyone. Therefore, if your organization wants a more restrictive implementation, it must be implemented in addition to these tools.

The CoE Starter Kit is a set of templates to help you get started, and - when you are ready - can be extended to fit your specific requirements, read about extending the solution here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#extending-the-starter-kit

You can read about the Sample Audit Process here https://docs.microsoft.com/en-us/power-platform/guidance/coe/example-processes and modify the necessary flows to send notifications according to your requirements, and take inspiration from the Developer Compliance Center but replace it with a data source that doesn't require a premium connector - you could even use Microsoft Forms for this! 

The CoE Starter Kit team provides these templates to share best practises and provide a starting point and helping hand to organizations getting started with setting up a CoE, but detailed implementations would be the responsibility of the organizations - sometimes this is also accomplished by working with a Microsoft Partner https://powerapps.microsoft.com/en-us/find-a-partner/
