### ISSUE TITLE
Deleting Environments not showing deleted in CoE

### ISSUE THREAD

**Issue by gregwilliams14** [microsoft/powerapps-tools#318]
I am deleting environments from the Admin center however, the deletions are not reflected in the COE starter kit. Something i need to do to force this?
Greg

**Comment by JeneferM-MSFT** [comment]
They will be updated as deleted in the CoE when the sync flows run. 
If you look in the Admin | Sync Template v2 flow of the Core solution you will see these steps:
![image](https://user-images.githubusercontent.com/62659043/83551742-9a234b80-a4bd-11ea-8f84-cc16ede5464f.png)

Please let us know if this does not occur. 
Thanks for using CoE!

**Comment by gregwilliams14** [comment]
i should have known that - thanks

**Comment by JeneferM-MSFT** [comment]
Glad to help!

**Comment by manuelap-msft** [comment]
@gregwilliams14 we were missing a filter on the Power BI dashboard to filter out deleted environments, which might be why you've experienced issues. We have fixed this yesterday and you can download the updated dashboard from here https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard_2020-06-02_advanced.pbix

There is no need to update the whole CoE Starter Kit but you will need to follow steps 1-6 to configure the dashboard https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#option-2-configure-the-power-bi-dashboard-by-using-the-pbix-file

Hope that helps!

**Comment by gregwilliams14** [comment]
The pbix file will not open.  Also why want the PowerApp “Power Platform Admin View” update after I delete environments?

[cid:image002.jpg@01D63975.A6BB2DD0]

**Comment by manuelap-msft** [comment]
Are you getting an error message when trying to open the dashboard? I have just tested on my side and it looks okay, so in order to help further could you let us know the steps you are performing?

On the model driven app, for Environments there currently isn't a filter set to only show active environments although that is probably something we should update on our end. I can walk you through the steps to update this on your side, or we can comment here when we added this in the next release.

**Comment by gregwilliams14** [comment]
I get the error when trying to open the dashboard.

Are you offering to have a call to set up the app?

Greg
