### ISSUE TITLE
[BUG]: O365 Audit Logging "requires" lower security?

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/powerapps-tools#350]
**Describe the bug**
- It [appears](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-1-connect-to-the-audit-log-by-using-basic-authentication) that in order to setup O365 audit logging, you have to be a Global Tenant Admin **without** MFA enabled. 
- What if we have MFA enabled? 

Is there any way to get the PowerBI dashboard and audit logging capabilities while sticking to good security practices?

**Screenshots**
![image](https://user-images.githubusercontent.com/42788729/85325441-7cc01c80-b480-11ea-8fe2-95e7e58fa3d6.png)

**Comment by manuelap-msft** [comment]
If you have MFA enabled you can use Option 2: Connect to the audit log by using an Azure app registration https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration

**Comment by JeneferM-MSFT** [comment]
I think there is also a bit of confusion here. You dont need Global Tenant Admin in order to run the solution, that is just an account that can give you permission to the audit logs. 
From the instructions:

- Global tenant admins have access to the audit logs by default and can grant access to the audit logs for other user accounts or groups through the Exchange admin center.

If the user/account which will run the sync flows does not yet have access to the audit logs ( [protection.office.com](https://protection.office.com/homepage) > Search > Audit Log Search), then a Global Tenant Admin can grant them. If they already have access, you are set.

**Comment by SeaDude** [comment]
Hm. Could you give a specific example that would work in the following scenario:

- Large company (100k employees)
- 1 Global Admin
- Sub-Sub-Subordinate is the Flow "Expert" who is deploying the CoE
- We don't want the Sub-Sub-Subordinate to have the "keys to the kingdom" (Read perms on the O365 Audit Logs)
- We also don't want to burdon the Global Admin with the details of deploying the CoE Flows!

What would someone do in this case, specifically?

Is there an option for sharing the Flow with the GA as a Co-owner and having them create a connection for the specific Flow actions that require Read Perms to the O365 logs? 

What are the security risks with this approach? Could the Sub-Sub-Subordinate re-use this connection in building the Flow to circumvent or impersonate? 

Thank you!

**Comment by JeneferM-MSFT** [comment]
Still a misunderstanding here. 
Can you check to see if you have permissions to view audit logs?  protection.office.com > Search > Audit Log Search
If so, you are all set. You can set up the CoE and turn on the flows, which populates the CDS with the required lines from the audit logs. 
You can then share the resultant dashboards with whomever you would like. 
If you do not have permissions to view the audit logs, you will need to request them. That is where the Global Admin comes, to grant you access to the audit logs.

**Comment by SeaDude** [comment]
The person deploying the CoE does not have read permissions for the O365 logs. If they are granted these permissions in order to make a connection in the CoE Flow, what else can they do with these permissions? 

Could they go to https://protection.office.com/unifiedauditlog and peruse logs at their leisure? 

To reiterate, we don't want the Sub-Sub-Subordinate to have a bunch of permissions they don't need in their daily duties just to setup a connection in Flow. 

It looks like @manuelap-msft 's solution will be the path to take. But one question I have before embarking on those steps:

- Do the `client secret` and other credentials required by the Custom Connector remain in plain text once pasted into the fields or are they obscured? 

If the Custom Connector is shared, I wouldn't want that person to see/recover the credentials from the custom connectors configuration. 

Thank you

**Comment by manuelap-msft** [comment]
Hello,

yes, a user with the ViewOnly permissions to the Audit Log will be able to see the Audit Logs under protection.office.com as well - there currently is no Privilege that gives you Read Only permission to just the Power Platform audit logs. 

For just Power Platform activities, a Power Platform Admin can make use of the out of the box analytics in the Admin Center:
https://docs.microsoft.com/en-us/power-platform/admin/analytics-powerapps

Client ID and Secret are obscured.

**Comment by JeneferM-MSFT** [comment]
Closing out issues with not additional steps to be done. Please reach out or create a new bug if you find additional issues.  
Thanks for using CoE
