### ISSUE TITLE
[BUG]: Does COE Apps dashboard report shows only canvas apps or model driven apps as well?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#374]
**Describe the bug**
It seems that COE Apps dashboard  doesn't show all apps across the tenant, same as "Get-AdminPowerApp" whether shared with MPP Admin/GA Admin OR not - it seems this only shows all canvas apps and some model driven apps.

Can you please clarify which APPs will be visible in COE Apps dashboard if run by MPP/Global Admin?

**Component (please tell us which flow or app you are experiencing issues with):**
 -  Core Componenet
 - Version 1.44
 - Power BI Report

**To Reproduce**
1. Go to Power BI Dashboard
2. Click on 'Apps'
3. Locate to 'Apps Creation Trend' tabular report
4. See that some apps are not visilbe, while it's visible in UI

**Expected behavior**
All apps types across the tenant should be visible in PowerBI dashboard for Power Platform Admin whether shared/not shared

**Comment by manuelap-msft** [comment]
Hello,

you're using quite an old version of the CoE Starter Kit, so would upgrading to the latest version so to make sure you have the latest bug fixes and features. 

The CoE Starter Kit does show model driven apps, however the admin would need to be a System Administrator in the environments with model driven apps. Ensure your role has the correct level of access. Additionally, only published model driven apps (not those in draft status) are shown. 

Hope that helps,
Manuela

**Comment by dips23** [comment]
Hello,

Thank you for the response with more information, MPP Admin have "System Administrator" role in the environment of MDA Apps which is not being visible in COE App.I have also published it's customization.

However, When I try to change the OrgURL in latest PBI file, I am facing following errors:

![image](https://user-images.githubusercontent.com/13658386/87431335-1b651680-c604-11ea-82c1-50f0f2471c27.png)

Can you please share if I am missing anything here?

Thanks,

**Comment by manuelap-msft** [comment]
Are you logged into Power BI with the admin account that has access to the entities?

In the pop-up "Apply your changes" currently I can only see "failures with other queries". If you scroll down, you will find the query that is failing (& causing other queries to fail) - could you comment back with that specific failure.

**Comment by dips23** [comment]
I am logged into Power BI as "MPP Admin" that has access to all entities in the environment, however when I check the "admin_app" entity, I see that couple of MDA apps are not listed in the table, even after publishing the customization related to that - I assume in this case, I will not see the app in PBI Report - is that correct? does this require any specific flow to run?

While regarding pop-up errors, when I scroll down I see following errors:
![image](https://user-images.githubusercontent.com/13658386/87434799-89abd800-c608-11ea-975c-3f2d552c0ff1.png)

Do I require to update anythin anywhere else?

Thanks again for your time and help!

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

when you navigate to make.powerapps.com > Solutions > Center of Excellence Core Components and search for PVA do you see the three PVA entities and one flow
![image](https://user-images.githubusercontent.com/55705669/87435744-109a8980-c5e4-11ea-99aa-8b1a8de92e09.png)

**Comment by dips23** [comment]
As MPP Admin,I do not see any of these components available under make.powerapps.com > Solutions > Center of Excellence Core Components.This pops up following questions:

1. Are these components compulsory to run "Power BI Dashboard Report" ?
2. Do I require to remove old "Core" components and add new core components from latest COE Kit?
3. Does these components would need "Global Admin" rights to configure?

Thanks and Regards,
Dipti

**Comment by dips23** [comment]
Thanks for the suggestions!

I have updated the COE core components accordingly and now I can see PVA customizations in the solutions which I have upgraded>published on the existing core components.

Then, I published latest PBI report and I (MPP Admin) see the current org's apps count, however I yet do not see a specific model driven app which is shared with me with owner rights and that says probably the count of all apps can not be "True" 

Further, under "Apps" report when I click "App Type" filter, It does not show "Model Driven Apps" filter as indicated in the following screen:

![image](https://user-images.githubusercontent.com/13658386/87637824-6eec7700-c760-11ea-9cf4-13af73f33557.png)

Questions:

1. What could possibly missing at my end? (I confirm that the count of Apps in PBI Report and "admin_App" entity is same.)
2. On the other hand, "Get-AdminPowerApp" has different results in terms of count and it's apps, can you please share how PBI report gathers Apps details from the different environments with it's limitations?

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

the Power BI dashboard is based on the Common Data Service entities, such as admin_App, admin_Flow that are part of the CoE Starter Kit. Those entities get populated by the sync Flows - Admin | Sync Template v2 (Apps, Flows, Connectors,...). Those flows use the admin connectors - [Power Platform for Admins](https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/), [Power Apps for Admins](https://docs.microsoft.com/en-us/connectors/powerappsforadmins/), [Power Automate Management ](https://docs.microsoft.com/en-us/connectors/flowmanagement/) to gather information about resources in your tenants. So it uses "Get Apps for Admins" per environment to gather information about canvas apps.

Some resources, such as model driven apps and chatbots do not have a management connector but their information is stored in underlying system entities - for model driven apps, that entity is called appmodule and for chatbots it is called bot. Those entities exist in each environment (and are system generated) and what the CoE Kit does here is gather information from those entities.

Because this information is stored in CDS entities, it adheres to CDS security roles and the user running the Sync Template v2 (model driven app) flow will have to have System Administrator access to each environment in order to view the data here. The other limitation is that for environments of type [Developer](https://docs.microsoft.com/en-us/power-platform/admin/environments-overview#types-of-environments) (those created through a community plan) this information is not available, as only the user with the community plan has access to the environment and access can't be granted to admins.

You could look at the Admin | Sync Template v2 (model driven apps) to see if there's any errors in getting information from the environments. 

Hope that helps,
Manuela

**Comment by dips23** [comment]
Hello,

I confirm that MPP Admin has "System Administrator" role in the environment of MDAs, however following connectors are not granted by GA yet, therefore those flows are not currently functions:

Power Platform for Admins,
Power Apps for Admins,
Power Automate Management

apart from access on above connectors, does this report also require "Dynamic 365 Role" in addition to "MPP Admin Role" ?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
No, the Power Platform Service role is sufficient. You can see a list of all the connectors used as part of the CoE Kit here in the 4th bullet point https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

**Comment by JeneferM-MSFT** [comment]
Closing out issues without action items for us. Let us know if you need more help after getting access to those connectors. And thanks for using COE
