### ISSUE TITLE
[BUG]: Clarifications on Apps/Flows audit process

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#393]
**Describe the bug**
Clarifications on Apps/Flows audit process

**Component (please tell us which flow or app you are experiencing issues with):**
 - Audit Solution 
 - CoE Starter Kit - v2.1
 - Apps and Flows:
Developer Compliance Center (canvas app)
Flow – Compliance detail request
Business Process Flow for Auditing resources

**To Reproduce**
COE Starter Kit v2.1 is configured in the MPP, however I require to know about the following details for the Auditing process:

1. Does Dev Compliance Center App/Flow consider all the apps and flows OR only Canvas Apps of all MPP environments ?
2. Is it possible to include customization for the compliance policy such as whether app is created in the right environment or not? 
3. Does COE Start Kit include import/export process of apps from one environment to another environment?

Thanks for your time and help!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
1) The app only allows for Canvas but the Flow checks for both Canvas and MDA. This is a good catch I have posted an issue for us to address this inconsistency. Flows are not considered at all here wrt the targets of the compliance search. 

2) That customization would be possible for you, yes. We could not implement it though as it would be too policy specific. We cannot assist with customization unfortunately due to funding. 

3) The kit does not include that specifically, but the product does. And the archival flows is a good place to look to start learnign about that as it programatically does the backup side of such a migration action already. 

Hope that helps, and thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
Closing out issues without furst activity. Thanks for using CoE!
