### ISSUE TITLE
[BUG]: Welcome email Power Automate is not triggered

### ISSUE THREAD

**Issue by AnaInesNini** [microsoft/powerapps-tools#401]
**Describe the bug**
1. Latest Welcome email template flow has been installed and config as per MS doc
2. The flow doesn't trigger and error message below is display

 - **Solution:**: Nurture Components
 - **Flow:** : Welcome email Flow template

**Welcome email error:**
Insufficient privileges to complete the operation.
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2020-07-24T00:15:30",
      "request-id": "d041eb29-362a-46d9-97bc-b41fcac07d9b"
    }
  }
}

**Expected behavior**
email should be sent

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot of where you are seeing this message? 
What action are you performing to anticipate that the flow should trigger?

**Comment by AnaInesNini** [comment]
Here you go,  I have requested as well to add the service account as owner of the SG maybe this will solve the issue
![Issue_welcome email](https://user-images.githubusercontent.com/48518536/88846839-78f18980-d1e6-11ea-972b-fbd29bad2bd0.jpg)

Secondly, we have created a new flow in the  same environment but flow didn’t get triggered. Condition is when the record is created in the organization:
![isue_welcome email 2](https://user-images.githubusercontent.com/48518536/88846857-81e25b00-d1e6-11ea-9eb7-872ee5d3e762.jpg)

**Comment by JeneferM-MSFT** [comment]
For the trigger:
A record is created in Makers when a **new** maker occurs. 
In other words, the first time Joe ever makes a Power App / Flow / Power Virtual Agent, they will get the welcome mail. 
Subsequent times that Joe creates more of these they will not. 
So in order to trigger you will need to use an account that does not yet exist in the Makers table.  

For the permissions:
Yes you need to run in the context of someone that has rights to add to that group.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without further activity. Thanks for using CoE!
