### ISSUE TITLE
[FEATURE]: Include Unique, Domain and Friendly Names in Environments Entity

### ISSUE THREAD

**Issue by jensneumann** [microsoft/powerapps-tools#404]
**Describe the feature**
For Environments there are different names (friendlyName, uniqueName, domainName und dispayNam) used in different connector actions. Therefore all different names should be stored in the CoE Core Components Entity Environments and not only the displayName.

**Impact**
Improves working with different connectors and actions of the power platform in which an environment identifier is required, but which used either the unique name, org name, friendly name or even a composition like orgname.hostname suffix in the Common Data Service list all entity data action.

**Expected behavior**
Add the fields Unique Name, Friendly Name and Domain Names (all Text) to the CoE Envionments Entity and fill it via the Flow  "Admin |Sync Template v2".

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE, and for the suggestion. 
Can you please give examples of each of these? I can look to see if they are offered in the connectors provided.

**Comment by JeneferM-MSFT** [comment]
I have found two places where this is useful for calling other connectors, and have added this to the toolkit. 
The next version of Core will now be these fields in the environment entity, and they are called from the sync flows. 
1) **_hasCDS_** which will be true if the envt has a CDS and false otherwise
1) **_Environment CDS Metadata Name_** which will house names like org12ab123.crm

Please let me know if you have other examples where these would be useful to store.
Thanks for using CoE and for the good suggestion.

**Comment by jensneumann** [comment]
Thank you for the quick solution! I found it via the **List Records** action of the **Common Data Service**" connector which requires the unique Environment name plus the region identifier. Be aware that there are two different metadata names, one is unique name,the other is orgname.

**Comment by JeneferM-MSFT** [comment]
This has now released. Thanks for helping make CoE great!
