### ISSUE TITLE
"Archive and Clean Up Approval" process

### ISSUE THREAD

**Issue by LatifulKhan** [microsoft/powerapps-tools#410]
As part of "Archive and Clean Up Approval" process flow it sends email with "Approve" and "Reject" , clicking this link generates "permission error to access CDS database", how to resolve this?

**Comment by JeneferM-MSFT** [comment]
Did you use a security group for permissions when setting up the CoE? 
You can check by going to the [admin center](https://admin.powerplatform.microsoft.com/environments), and selecting the environment. 
Under Details > Security Group, it will either show the name of the security group or "Not Assigned"
![image](https://user-images.githubusercontent.com/62659043/89442220-47575180-d703-11ea-8959-234c8c027c01.png)

**Comment by Craig-Humphrey** [comment]
I'm getting something similar.
I didn't have the CoE Environment set with a security group, but I've changed that now, but it's not made a difference.

I've checked the security roles applied to my account and it has Approvals User, Common Data Service User and System Administrator.

I get the following error when I attempt to approve a "to be archived" app or flow:

Encountered a general permissions error trying to access the CDS database. This could be caused by modification of the approvals administrator or user roles, or by an incompatible plugin. Detailed message: 'Message: Principal user (Id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, type=8, roleCount=1, privilegeCount=94, accessMode=4), is missing prvReadAsyncOperation privilege (Id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) on OTC=4700 for entity 'asyncoperation'. context.Caller=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Code: 0x80040231 InnerError: Type: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]] Message: Principal user (Id=dfa23889-d7d6-ea11-a813-000d3acae853, type=8, roleCount=1, privilegeCount=94, accessMode=4), is missing prvReadAsyncOperation privilege (Id=e84acc8f-0c61-43e3-a716-20964a483bdf) on OTC=4700 for entity 'asyncoperation'. context.Caller=dc0161b6-a11e-4722-b36d-ca1686abcf8f StackTrace: at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters) at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Upsert(Entity entity) at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Update(Entity entity, UpdateOption updateOption) at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateEdmEntity(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, EdmEntityObject entityObject) at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta) at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0() at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger,

**Comment by JeneferM-MSFT** [comment]
Sorry for not being clear before. The reason I was asking about the Security Role is because we suggest you **_do not_** use one.

Flow approvals use CDS entities under the covers, but do not require licenses/permissions to the CDS generally speaking. 
Once you add the security role users will need to be authorized to the CDS / the environment as a whole to have access to any part of it, including approvals. 

Permissions here work out of the box for most people, as long as they aren't using a Security Role, so I'm afraid you'll need to reach out to product support if you are having approvals permissions issues.

**Comment by LatifulKhan** [comment]
> Sorry for not being clear before. The reason I was asking about the Security Role is because we suggest you **_do not_** use one.
> 
> Flow approvals use CDS entities under the covers, but do not require licenses/permissions to the CDS generally speaking.
> Once you add the security role users will need to be authorized to the CDS / the environment as a whole to have access to any part of it, including approvals.
> 
> Permissions here work out of the box for most people, as long as they aren't using a Security Role, so I'm afraid you'll need to reach out to product support if you are having approvals permissions issues.

**Comment by LatifulKhan** [comment]
Thanks @JeneferM-MSFT what do you mean by product support? It does not work if I add user to approval role, even I tried by giving all roles and power platform admin access, no luck :) 
Could you confirm that it is actually working to CoE kit as I tried it in multiple environments :(

**Comment by Craig-Humphrey** [comment]
LOL I'll try raising a support request - but it might be interesting given: "Microsoft Support won't help you with issues related to this kit, but they will help with related, underlying platform and feature issues." (From https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support)

**Comment by JeneferM-MSFT** [comment]
Correct, this set of flows continues to work for most CoE users, so the issue is probably not with our toolkit but with the way permissions are set up for you, or with the product itself. 
Please let us know if you discover something that can be generalized for the toolkit and we will try to include it in the FAQ
Thanks for using CoE

**Comment by LatifulKhan** [comment]
Until we find a resolution for this permission issue we really can not use it :(

**Comment by JeneferM-MSFT** [comment]
Only this one set of flows should be blocked your permissions issues.
Monitoring, nurture, and the other compliance features do but rely on approvals. 
I suggest you check to make sure you don't rely on a security group, as stated above too

**Comment by LatifulKhan** [comment]
I do not have any security group assigned. If approval does not work here then does it not mean that other approval will also not work?

**Comment by JeneferM-MSFT** [comment]
Correct. Your Environment does not seem to be supporting approvals. But this approval flow is only one small part of the CoE solution. Most of the toolkit does not rely on it. The entire Core solution which focuses on Monitoring/Aggregation/DLP/Finding Orphaned Apps is not impacted for example.

**Comment by JeneferM-MSFT** [comment]
In summary, the Approvals Users is a Security Role that's automatically created and not shipped with the CoE Starter Kit. If there's any issues with how it is populated out of the box, please raise a Service Ticket and Support can log this as an issue accordingly.

**Comment by LatifulKhan** [comment]
What will I have to do to this environment to support approval?

**Comment by JeneferM-MSFT** [comment]
Again, sorry, you are hitting an issue either with the product or your tenant configuration, not the CoE toolkit. We cannot support you with that, you'll need to contact product support.

**Comment by JeneferM-MSFT** [comment]
We have a local repro of this now so re-opening. Will let you know what we hear.

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE and posting this. The product team made some shifts which require we make some changes too. 
Can you please see if the attached resolves this for you? 
[CenterofExcellenceAuditComponents_1_19_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066166/CenterofExcellenceAuditComponents_1_19_managed.zip)

**Comment by LatifulKhan** [comment]
![CoEError1](https://user-images.githubusercontent.com/57658405/90077081-579bac00-dd55-11ea-9388-4e823fc94f34.PNG)

**Comment by LatifulKhan** [comment]
@JeneferM-MSFT  do you know what does it mean? Do I need to delete old solution?

**Comment by JeneferM-MSFT** [comment]
Sorry someone had added components to the solution I was unaware of. Try this instead. 
No need to delete the old, in fact dont do that. Instead upgrade and chose to overwrite customizations. 

[CenterofExcellenceAuditComponents_1_20_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066423/CenterofExcellenceAuditComponents_1_20_managed.zip)

**Comment by Craig-Humphrey** [comment]
I've just upgraded to 1.20, but that hasn't changed the permissions issue with existing Approval tasks.
I haven't generated any new approvals to check if new ones are fixed.

Should it have fixed the permissions issue?

I still haven't logged it with support - too busy - will try to get that done this weekend.

**Comment by JeneferM-MSFT** [comment]
Craig, be sure to hit overwrite when you install the upgrade. It is not the default. 
![image](https://user-images.githubusercontent.com/62659043/90258400-59b94580-ddfd-11ea-9c0f-77f462ddae58.png)

**Comment by Craig-Humphrey** [comment]
Thanks Jenefer.

Just did an upgrade/overwrite - but I still get the same permission error.

Including again, just in case there's a fine detail difference:

Encountered a general permissions error trying to access the CDS database. This could be caused by modification of the approvals administrator or user roles, or by an incompatible plugin. Detailed message: 'Message: Principal user (Id=dfa23889-d7d6-ea11-a813-000d3acae853, type=8, roleCount=1, privilegeCount=94, accessMode=4), is missing prvReadAsyncOperation privilege (Id=e84acc8f-0c61-43e3-a716-20964a483bdf) on OTC=4700 for entity 'asyncoperation'. context.Caller=dc0161b6-a11e-4722-b36d-ca1686abcf8f Code: 0x80040231 InnerError: Type: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]] Message: Principal user (Id=dfa23889-d7d6-ea11-a813-000d3acae853, type=8, roleCount=1, privilegeCount=94, accessMode=4), is missing prvReadAsyncOperation privilege (Id=e84acc8f-0c61-43e3-a716-20964a483bdf) on OTC=4700 for entity 'asyncoperation'. context.Caller=dc0161b6-a11e-4722-b36d-ca1686abcf8f StackTrace: at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters) at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Upsert(Entity entity) at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Update(Entity entity, UpdateOption updateOption) at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateEdmEntity(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, EdmEntityObject entityObject) at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta) at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass11_0`2.<InvokeActionAndLogMetric>b__0() at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger,

**Comment by JeneferM-MSFT** [comment]
If you have any of the old flows around (you did a save-as for example) this will still repro. 
No flows with a trigger based on that entity can be turned on anymore.

**Comment by Craig-Humphrey** [comment]
FYI Deleted the solution and re-imported it.   Now the Approve/Reject for Archiving apps is working.

Not sure why over-write didn't fix it.

Thanks guys!

**Comment by Craig-Humphrey** [comment]
Yes, suspect I didn't bother re-copying the flows after updating the solution.
