### ISSUE TITLE
Admin | Sync Template V2 (PVA) does  not check for environment being deleted.

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#415]
**Describe the bug**
When a Record is updated (Trigger for Flow) the flow does not check to see why the record has been updated

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution 1.54 
 - Version 1,54
 - Sync Template V2 (PVA(

**To Reproduce**
Sync runs at a timed period
Create Environment - watch flow run
Delete environment watch flow fail

**Expected behavior**
I expect the flow to cater for deletions of environments

**Screenshots**
{
  "error": {
    "code": "EnvironmentNotFound",
    "message": "The environment '17c78fa3-9465-4ded-8b61-ecc83170586e' could not be found in the tenant '4e7056d6-0830-41be-a136-93b24c588169'."
  }
}

**Additional context**

**Comment by JeneferM-MSFT** [comment]
This is not an area we will be fixing. 

Note that clean ups from deletions in the environment can be cleaned up by enabling the following flow: **Admin | Sync Template v2 (Check Deleted)**

This flow runs weekly, and compares CoE to the tenant to determine if any objects were deleted since last run. Either just marks them as deleted (if env var *Also Delete from CoE* = no) or deletes them from the CoE (if *Also Delete from CoE* = yes).

Thanks for using CoE!
