### ISSUE TITLE
Unable to "Configure the CoE Settings entity" in Powerapps (installation COE-starterkit)

### ISSUE THREAD

**Issue by Frejen** [microsoft/powerapps-tools#443]
Today we have a couple of environments configured and working. We want to install COE-starter kit and have created an environment "Companyname COE" with common data service (CDS) and set DLP policy. 
After this we imported CoE Starter Kit (Core components) and configuration of enviroment variables have been made. 

With the starter kit there was a number of apps that automatically got owner during the import. 
We´ve followed the steps on the following pages: 

Prereqs: https://docs.microsoft.com/en-US/power-platform/guidance/coe/setup
Configuration: https://docs.microsoft.com/en-US/power-platform/guidance/coe/setup-core-components 

Problem: We get a problem under the task: "Configure the CoE Settings entity"
We follow the task: 
1. Go to make.powerapps.com, select Apps, and open the Power Platform Admin View model-driven app in Play mode. 
2. In the left navigation, select Configure. 

We do not have a visible meny for "configure" and cant get past this step. 
We´ve tried different permissions, licenses, adding users etc.

Logged in with administrator account permissions/regular user. We have power apps admin account and dynamics 365 admin, and power apps premium license. 
Thankful for suggestions on what to do. Since we are unable to follow the steps in the guide to get past this.

**Comment by JeneferM-MSFT** [comment]
Can you please share a screen shot of what you see when you go to play mode? Here is what mine looks like: 
![image](https://user-images.githubusercontent.com/62659043/91858429-0842f000-ec1e-11ea-8c78-ad61a6453884.png)

**Comment by Frejen** [comment]
As you can see, we have no data and not so many menu alternative. Sorry for swedish language settings.
![image](https://user-images.githubusercontent.com/37864914/91874746-e2980400-ec7a-11ea-9345-c3b21b437356.png)

**Comment by Frejen** [comment]
We have some thoughts about the ownership of apps. Did the import as adminuser but the model-driven app gets my regular user as owners
![image](https://user-images.githubusercontent.com/37864914/91874992-30147100-ec7b-11ea-8e1e-10b67c10e0b1.png)

**Comment by JeneferM-MSFT** [comment]
The below doesn't get at the issue you are seeing, but the owner of this app is away so hoping to just get you unblocked for now. 

Can you see the entity if you go to the entity view? 
![image](https://user-images.githubusercontent.com/62659043/91875593-87412400-ec30-11ea-8337-a37a9d018319.png)

And if so, can you edit it through another means? (ex make a different Power App, or my favorite way, open in Excel)
![image](https://user-images.githubusercontent.com/62659043/91875695-b6579580-ec30-11ea-9f27-4f88ccaeea2f.png)

**Comment by manuelap-msft** [comment]
Hello! 

I recall seeing this issue before in a setup where the language was not English - all the subgroups in the model driven app had the same name (My Group instead of Monitor, People, Settings) and thus were not displayed when the app played.

Could you please try the following?

1. Navigate to the Center of Excellence - Core Components solution
1. Open the Power Platform Admin View (Site Map) in Edit mode
![image](https://user-images.githubusercontent.com/55705669/92224681-0e450500-ee9a-11ea-8ed9-fff6a5b80c11.png)
1. Check if the groups are displayed like this, or if they all show My Group has header
![image](https://user-images.githubusercontent.com/55705669/92224731-1ef57b00-ee9a-11ea-9273-c456ed4c2323.png)
1. If the all show My Group, select the header (in my screenshot that's Monitor, People and CoE Settings) and change the Title and ID under Properties to be unique values
![image](https://user-images.githubusercontent.com/55705669/92224799-3af91c80-ee9a-11ea-9b8f-23e0030ff560.png)
1. Save and Publish the Site Map

**Comment by Frejen** [comment]
Now it´s working. We uploaded english to our Dynamic365 environment and selected english for Power Apps and now we can see all information like the guide showed.

**Comment by manuelap-msft** [comment]
That's great, thanks for confirming!
