### ISSUE TITLE
[BUG]: Data for other services like Forms, Stream, PowerBI, ... is missing

### ISSUE THREAD

**Issue by LoebelM** [microsoft/powerapps-tools#479]
**Describe the bug**
I need to have access to further service data from the audit log. Only Flow and PowerApps information can be received.
Data for Stream or Forms is not accessible.

Furthermore I need to have all this data stored in an AzureDB to anonymize PII before using it for reporting.
How can this be done?

**Component (please tell us which flow or app you are experiencing issues with):**
all

**To Reproduce**
the data is missing after the export is done as described in the documentation

**Expected behavior**
I would like tom have all data from Audit Logs exported to Azure SQL Database using the custom connector

**Screenshots**

**Additional context**

**Comment by LoebelM** [comment]
to get in contact with you this way was recommended from MS Support colleagues where I opened a case

**Comment by manuelap-msft** [comment]
Thank you for your interest in the CoE Starter Kit! 

The CoE Starter Kit is developed by the Power Apps and Power Automate Engineering team, it's a collection of templates, components and tools that are designed to help you get started with developing a strategy for adopting and supporting Power Apps and Automate in an organization. 
It is not officially part of the product, nor is it supported as it acts as a sample representation of features. Read more about our [support model](https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support) here.

As this set of templates comes out of the  Power Apps and Power Automate Engineering team, other product groups like Power BI, Stream or Forms are **out of scope**. I would recommend checking out the out of the box admin functionality to see if this suits your needs; we also have some customers who work to extend the kit to include additional features either themselves or with a partner. 

In order to choose a different underlying datasource for Audit Log or other data, you can modify the Flows part of the Audit Log solution to write data to your chosen data source. You would then also have to modify the Power BI Dashboard to get the usage (session and unique users data) from your data source rather than from the CDS entity. 

Hope this helps!
