### ISSUE TITLE
[BUG]: Unable to create Office 365 Management API connection when importing AuditLogs component

### ISSUE THREAD

**Issue by petepuu** [microsoft/powerapps-tools#484]
**Describe the bug**
When importing CenterofExcellenceAuditLogs_1_2_managed solution it is required to define connections during the import. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - AuditLogs v 1.2

**Steps to reproduce the behavior:**
1. Import CenterofExcellenceAuditLogs_1_2_managed.zip package using new import UI
![image](https://user-images.githubusercontent.com/8307644/94193172-adb55080-feb8-11ea-9659-cacc1e78d67f.png)

2. Add new connection for Office 365 Audit / Management API connector

![image](https://user-images.githubusercontent.com/8307644/94193325-e523fd00-feb8-11ea-8784-ffc0888c8863.png)

3. Following error is thrown 

![image](https://user-images.githubusercontent.com/8307644/94192871-37185300-feb8-11ea-83c5-6ea4f0df0889.png)

**Comment by JeneferM-MSFT** [comment]
Hello. We had to back track on this 1.2 version of the audit logs due to some issues we found. 
Please redownload the zip, or see below, to backtrack to 1.17

[CenterofExcellenceAuditLogs_1_0_0_17_managed.zip](https://github.com/microsoft/powerapps-tools/files/5279234/CenterofExcellenceAuditLogs_1_0_0_17_managed.zip)

Thanks for using CoE!

**Comment by petepuu** [comment]
Ok good to know. Thanks!
