### ISSUE TITLE
[BUG]: Transparency issue prevents button click in Set App / Set Flow Permissions apps

### ISSUE THREAD

**Issue by morismm99** [microsoft/powerapps-tools#489]
CoE Core Components version 1.70.1

In the Set App Permissions and Set Flow Permissions canvas apps:

In the Orphaned groups, when selecting and choosing to delete an app/flow, the transparent screen as part of a group of items was on the front, which prevented an end user from pressing the buttons to submit/cancel. I fixed on my apps, but wanted to bring this app in case it can be fixed in the template apps.

Also, fixed the global variable for settings in the Set App Permissions app, as it was missing it entirely.

In the PowerApps Button Archive App flow:

In the last condition on whether to delete a flow based on the delteApp variable being set to true/false, the condition was false all of the time. This is because we were comparing a string with a boolean. I had to create an additional string variable, set that to true, and that fixed the issue.

**Comment by JeneferM-MSFT** [comment]
Hi there. Thanks for using CoE and submitting improvement suggestions!  I'm having a little trouble following you though, woudl you mind sharing your repaired apps here for me to investigate?

**Comment by JeneferM-MSFT** [comment]
Hello again. I have local fixed the transparent screen problem, but dont understand / cannot repro your concern. 

If you can please share your app with me here, or if you can share screenshots, then I can proceed.

**Comment by JeneferM-MSFT** [comment]
The fix to the transparency issue has been fixed in the new release for flows, but was missed for apps. 
This issue will stay open to track the fix for apps yet. 
For the other issues you mention, if you have more details on the other issues (can show screenshots or share your fixed app), please open a new bug for those. 
Thank you for using CoE, and helping make it great!

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
