### ISSUE TITLE
[BUG]: How can we confirm that CoE data in the CDS Environment is up to date?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#496]
Hello,

As per my understanding validating CoE data would be a manual task by checking MPP Admin center resources against the PowerBI report, however is there any other way to check and confirm quickly that CoE data in the CDS is up to date?

For example, as MPP Admin, I see 12 environments in the MPP Admin center, however Power BI Report shows - 14 environments, because COE Flows were turned off due to business issues for the temporary purpose.

Is there any way to refresh CoE data and make them uptodate? 

Thanks and Regards,
Dipti

**Comment by dips23** [comment]
Hello, 

I think there are couple of flows that manages the data up-to-date as follows, if I understand correctly:

Admin | Sync Template v2
Admin | Sync Template v2 (Check Deleted)	
Admin | Flow Archive and Clean Up - Start Approval
Admin | Flow Archive and Clean Up - Check Approvals and Archive

However, by any chance there is any quick and easy way to know that data is up-to-date or not?

Thanks,

**Comment by JeneferM-MSFT** [comment]
Hi there. If what you are wanting to do if cross check that our data is correct, after our data is up to date. Then yes that would need to be manual. And please do bring any discrepancies you find to our attention so that we can address. 

If what you are wanting is to know if our data is up to date:
The PBI report shows a date which will indicate whether or not the main sync flow (Admin | Sync Template v2) has been run. I did just notice that the auto-refresh isn't working though, so I've added that to my backlog to fix.

You can still see up to date though, if you open the report in PBI desktop you can refresh there and see that date.
![image](https://user-images.githubusercontent.com/62659043/94935764-4b44ed00-0482-11eb-961f-7efab098fa9a.png)

This main sync flow updates the "Environment" objects, and the rest of the sync flows key off that change. 
When Environment Foo is updated by that sync flow, it will trigger the apps flow for Foo, the MDA flow for Foo, etc. 

There isn't a way for us to know when all of those dependent flows have completed. But you can go and get a feel for how long that takes by looking at the runs for those. 

Hope that helps.

**Comment by JeneferM-MSFT** [comment]
Hi there. Cleaning up bugs so checking in to validate that this answers your question. Thanks again for using CoE

**Comment by JeneferM-MSFT** [comment]
closing issues without follow ups. thanks for using CoE!
