### ISSUE TITLE
[BUG]: Microsoft Flow Bug (Admin | Sync Template v2 (Check Deleted))

### ISSUE THREAD

**Issue by matrixzonee** [microsoft/powerapps-tools#498]
**Describe the bug**
In CoE Starter Kit, Environments are being marked as deleted incorrectly in CDS Entity "Environments" 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.23]
 - App or Flow [Admin | Sync Template v2 (Check Deleted)]

**To Reproduce**
1. Go to "Environment" Entity
2. Click on Data Tab
3. All the Environments will be marked to be deleted in the entity.

**Expected behavior**
CDS Environments should not be deleted if they exist. Because of the bug in the Admin | Sync Template v2 (Check Deleted), the Environments are being incorrectly marked as Deleted because of using old API Version in the flow.

**Screenshots**
Incorrect API Version "2018-06-01" used in "Get Environments" Step.
![image](https://user-images.githubusercontent.com/6177057/95053437-55682500-06e8-11eb-8a77-095f2ff89035.png)

**Additional context**
The correct API Version should be 2020-06-01 as is being used in other Flows in CoE Starter Kit

**Comment by JeneferM-MSFT** [comment]
Thanks for posting! I have created a helper flow to mark everything as not deleted, so that you can do a good cleanup.
[MarkObjectsNotDeleted_20201005181513.zip](https://github.com/microsoft/powerapps-tools/files/5329559/MarkObjectsNotDeleted_20201005181513.zip)

Can you please run that and then this updated clean up flow to see if it works? 
[CheckDeletedAPIvix_20201005190941.zip](https://github.com/microsoft/powerapps-tools/files/5329568/CheckDeletedAPIvix_20201005190941.zip)

Thanks again!

**Comment by matrixzonee** [comment]
Thank you..

**Comment by JeneferM-MSFT** [comment]
This is now resolved in the new release of Core. 
Thanks for using CoE and providing such great feedback!
