### ISSUE TITLE
[BUG]: DLP Canvas apps seemed to have been removed from the latest core components solution

### ISSUE THREAD

**Issue by jdiekman** [microsoft/powerapps-tools#512]
**Description**
Have the DLP customizer and editor been removed from the solution? We're unable to find them in any of the solution files. Previously we found these in the Core Components solution > canvas apps. 

**Component:**
 - Solution Core
 - Version 1.7.2
 - App or Flow DLP Customizer, DLP Editor

**Comment by manuelap-msft** [comment]
Due to a bug with the DLP Actions in the Power Platform for Admins Management Connector, the DLP apps had to be removed until that bug is fixed in the product

See our release notes:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/core-1.70#deprecation

As well as Known Issues for DLP:
https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#known-issues

We are hoping to put them back in the solution as soon as the bug is fixed.

Thanks for using CoE!

**Comment by MarinaHadzi** [comment]
Hi, is there any news about the DLP editor and DLP customizer bug fixing?

**Comment by shrutibahl** [comment]
hi, is there any update on the DLP Editor V2 app? When will it appear again in the solution?
