### ISSUE TITLE
Incorrect number of Apps shown in COE

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#527]
In our COE environment we've noticed that the environment app count is not the same as the actual number of Apps in the environment.

Microsoft Dynamics 365
2020 release wave 1 enabled
Server version: 9.1.0000.23177
Client version: 1.4.1476-2009.1

1. Go to Monitor
2. Click on environments
3. Scroll down to and open one of our environments
4. The number of Apps represented = 6

I was expecting to see 10 Apps as listed in the Power Platform Admin
We've rerun all the flows and can see the number of apps increase as it's running. Often the number will increase and then decrease before ending

**Comment by JeneferM-MSFT** [comment]
Can you please share what count you are referencing? Is this the calc field in the entity? The Power BI? We have several places we display this.
Are you seeing this for all environments or just some? 
Can you share a picture of the report you are referencing as well as a picture of the environment app list so that we can see the number you expect? 
Also, can you please share what version of Core you are running? 
![image](https://user-images.githubusercontent.com/62659043/96123679-67984f00-0eb0-11eb-9a24-5cd3f96d5159.png)

**Comment by SteveAsch** [comment]
Here's the count in COE
![image](https://user-images.githubusercontent.com/47640245/96274227-1f972c00-0f85-11eb-92c5-75530d439a04.png)
Here's the actual number it should be, 10. Note Bizview a custom model driven app is one of the missing apps.
![image](https://user-images.githubusercontent.com/47640245/96274441-58370580-0f85-11eb-94db-487cc1c1ebe1.png)
Here's the version of CORE
![image](https://user-images.githubusercontent.com/47640245/96274698-aea44400-0f85-11eb-8e74-d5a1a17b8516.png)

hopefully that helps

**Comment by JeneferM-MSFT** [comment]
The view that you are seeing looks a little different than mine. Can you please answer the questions below to help me debug your issue? 

1) How did you navigated to that view for apps? 
Ex: open **Power Platform Admin View** model driven app in play, select **Apps** under **Monitor** objections from the left menu.

2) Can you also please let me know if you added a filter to a particular environment or otherwise? And if so, where you did that filter? 

3) If you open the entity in Excel, do you see the correct number of apps?

**Comment by JeneferM-MSFT** [comment]
Hello, please let us know if you are still experiencing issues.

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no follow ups on our side. Thanks for using CoE!
