### ISSUE TITLE
[BUG]: Archive SharePoint document library has no backup for multiple Apps/Flows with same name

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#528]
**Describe the bug**
The flow "Admin | App Archive and Clean Up - Check Approvals and Archive" archives all Apps/Flows that are approved to be removed. If the remove environment variable is set to yes, the apps/flows are removed.
If you have multiple apps/flows with the same name, only 1 backup is added to the Archive document library.
This because the filename is [Title of Flow or Power App]-[Date].msapp
So if you have two Apps/Flows with the same name that get deleted on the same day you don't have a backup. You have only 1 because the file get replaced for every App/Flow with the same name.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance
 - Version: Latest
 - App or Flow: Admin | App Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
1. Create two Power Apps with the same name with two different user accounts
2. Run the flow and make sure that both are approved to be removed
3. Your 2 Power Apps are deleted but you only have 1 backup file in the SharePoint archive document library.

**Expected behavior**
A backup for every deleted Power App or Flow also if they have the same name.

**Solution:** Put the Flow or Power App ID in the .msapp & .json filenames so that the filenames are unique.

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE! We will look in to your issue. In the meantime, it sounds like you are able to make that change locally, is that correct?

**Comment by WouterF** [comment]
Yes I made the change locally. But when I upgrade the CoE it will be overwritten, no?

**Comment by JeneferM-MSFT** [comment]
Yes it will, as we do have an update coming which will not include this change. But I just wanted to ensure you were unblocked.

**Comment by WouterF** [comment]
Is the update already available? I see that the "CoEStarterKit.zip" file has been changed 2 days ago: https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit
Is it also possible to change the version history on that page so that we can see what has changed/added?
Thanks

**Comment by JeneferM-MSFT** [comment]
There was a release a few days ago, but it does not contain the fixes we are working on now.
I'm afraid we will not be able to fix your issue before the next release due to other urgent issues. 
You are welcome to wait to upgrade until your fix is complete though.

**Comment by WouterF** [comment]
Ok, thanks for the information.
I meant not the next release but the release after the next release. :)

**Comment by WouterF** [comment]
I have some additional feedback for the backup approval library. Right now, we only see the name and removal date of the app/flow.
We don't see what was the environment, who was the owner, who what was the id, ...
On top of avoiding duplicate backup file names, please add some metadata in the backup document library:

- Owner of the removed Flow/Power App
- Environment in which the Flow/Power App was
- Display Name of the Flow/Power App
- (Former ID of the Flow/Power App)

Thanks

**Comment by JeneferM-MSFT** [comment]
Hello. We cannot change the columns in the doc lib now for back compat reasons, but I can add the owner's name to the file name that is stored, thanks for that feedback.

**Comment by WouterF** [comment]
> Hello. We cannot change the columns in the doc lib now for back compat reasons, but I can add the owner's name to the file name that is stored, thanks for that feedback.

Yes please do that both for backups files of flows and backup files of apps. :)
Thanks

**Comment by JeneferM-MSFT** [comment]
ok we have this local fixed for the next release.

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**NOTE ALSO:** The way that the archival system works has changes now. 
1) No longer backing up for the user:
In the past we would back up the apps and flows for the owners in a SP library, and then they would need to find those backups later, or reach out to the Power Platform admin for assistance in finding those backups. 
We received some feedback from customers that this is problematic, and a few product changes were made which make this less reliable. 
As a result, we have moved to a system in which the users will be responsible for backup of their apps and flows themselves for later use, in the event they change their minds. 

2) An environment variable _ProductionEnvironment_ was added. If set to "no", it will send all approvals to the admin instead of the end user for your dev and test installations.

3) Changing the criteria to flag for archival:
Apps will now check for both modified and launched dates. By default, if they have not been launched NOR modified in 6 months, they will flag for archival
Flows will now be flagged for archival if they are not in the stopped state, as well as not modified in the last 6 months. 

Thanks for using CoE, and helping make it great with your feedback.
