### ISSUE TITLE
[BUG]: App Published Field for abandoned apps

### ISSUE THREAD

**Issue by tchinnin** [microsoft/powerapps-tools#531]
**Describe the bug**
The Flow fails if the abandoned App (no owner) has en empty LastPublishedTime because of the empty date inserted to the CDS.
DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - 1.70 Version
 - Admin | Sync Template v2 (Apps)

**To Reproduce**
Have an orphaned app with no published date
Run the Admin | Sync Template v2 (Apps) Flow

**Expected behavior**
The action shouldnt fail.

**Proposed solution**
Use the following formula into the App Published field of the Upsert App record (abandoned app) action
@{if(empty(items('Apply_to_each_App')?['properties']?['lastPublishTime']), null, items('Apply_to_each_App')?['properties']?['lastPublishTime'])}

**Comment by tchinnin** [comment]
Looks like the Upsert action in CoE doesn't accept null values....

**Comment by JeneferM-MSFT** [comment]
I believe apps are now published automatically now and so this should not occur in the future.
Is this an old app? Just one of them? 
Rather than complicating the flow further I'm wondering if we can just clean this up in your tenant.

**Comment by tchinnin** [comment]
Good to know. Is that true even for model driven apps ? 
I'm deploying CoE on a 2+ years old tenant so yes errors app are all from 2017.

**Comment by JeneferM-MSFT** [comment]
I have updated the flow to mark as Now if no published date exists. Will close this when we release with that fix. 
Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
