### ISSUE TITLE
[BUG]: App Archive flow sends approval request to app owners that do no exist anymore in AD

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#534]
**Describe the bug**
The "Admin | App Archive and Clean Up - Start Approval" flow sends approval request to app owners that do not exist anymore in AD.
We have an app that has an owner that has no account anymore in AD. Because the owner has no account anymore, he has no mailbox anymore and the approval action fails.
Probably this is the same for flows with an owner that does not exist anymore in AD.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance - Audit
 - Version: 1.24
 - App or Flow: Admin | App Archive and Clean Up - Start Approval

**To Reproduce**
1. Make sure that you have a Power App that has an owner that does not exist anymore
2. Run the Admin | App Archive and Clean Up - Start Approval flow
3. See that the approval actions fails for the app for which the owner does not exist anymore in AD

**Expected behavior**
If a Flow or Power App has an owner that does not exist anymore, the approval should be sent to an admin defined in the environment variables of the CoE.

**Comment by JeneferM-MSFT** [comment]
Hello. Yes we changed the way we track orphans and did not update these flows to look for that field now instead. 

Thanks so much for raising, we will work to fix.

**Comment by JeneferM-MSFT** [comment]
Hello. This appears to have already been working for the Flow side, and only repros for Apps. Please let me know if you have cases for flows. 
Here is the fix for starting the app archivals, local fixed in our environment. In case you want to update before we ship again
[Fixtoorphans_20201021154015.zip](https://github.com/microsoft/powerapps-tools/files/5417086/Fixtoorphans_20201021154015.zip)

**Comment by WouterF** [comment]
Hi,
I tried to import the fix "Fixtoorphans_20201021154015.zip" of your previous message.
It's not possible to import. I tried to import it in "My flows" and also in "Solutions".
![image](https://user-images.githubusercontent.com/5990852/97960447-cc5d1000-1db1-11eb-8683-a0865f3ebc1c.png)

![image](https://user-images.githubusercontent.com/5990852/97960471-da129580-1db1-11eb-8e9b-5ebcf3d0cd9f.png)

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**NOTE ALSO:** The way that the archival system works has changes now. 
1) No longer backing up for the user:
In the past we would back up the apps and flows for the owners in a SP library, and then they would need to find those backups later, or reach out to the Power Platform admin for assistance in finding those backups. 
We received some feedback from customers that this is problematic, and a few product changes were made which make this less reliable. 
As a result, we have moved to a system in which the users will be responsible for backup of their apps and flows themselves for later use, in the event they change their minds. 

2) An environment variable _ProductionEnvironment_ was added. If set to "no", it will send all approvals to the admin instead of the end user for your dev and test installations.

3) Changing the criteria to flag for archival:
Apps will now check for both modified and launched dates. By default, if they have not been launched NOR modified in 6 months, they will flag for archival
Flows will now be flagged for archival if they are not in the stopped state, as well as not modified in the last 6 months. 

Thanks for using CoE, and helping make it great with your feedback.
