### ISSUE TITLE
[BUG]: Sync Template v2 (Apps) Flow failed

### ISSUE THREAD

**Issue by aferland1** [microsoft/powerapps-tools#537]
**Describe the bug**
I installed the CoE Starter Kit yesterday, everything seems to work fine, I can start the Model-Driven App and I can also see some data in PowerBI. However, this morning I got an email saying that one flow failed to run. They ran for the first time last night.

When browsing to the flow and looking at the activity that failed, the action is "Get PowerApp Owner Profile for New" and the error is 404 - Request_ResourceNotFound - Resource 'xxxguidxxx' does not exist or one of its queried reference-property objects are not present.

**Component (please tell us which flow or app you are experiencing issues with):**
I am using the latest version (Downloaded on October 20)
The flow that fails is Sync Template v2 (Apps)

**Screenshots**
![image](https://user-images.githubusercontent.com/73231351/96715686-f5bd7b00-1371-11eb-8a39-87ff00aa0d13.png)

**Comment by JeneferM-MSFT** [comment]
Thank you for catching, we forgot to add the configure run after for this when we added it. 

I have fixed locally but in order to fix on your side while you await a new version, please do the following:
- go to the switch statement after this call and hit the three dots
![image](https://user-images.githubusercontent.com/62659043/96729128-6ff1fd80-137a-11eb-9e55-0e3f84815481.png)

- Select **_Configure run after_**, add a check for **_has failed_**, Done, and save the flow. 
![image](https://user-images.githubusercontent.com/62659043/96729453-c7906900-137a-11eb-8109-a618fba85c86.png)

**Comment by aferland1** [comment]
It worked! Thank you very much Jenefer
