### ISSUE TITLE
[BUG]: Users don't republish apps/flows after rejecting archival

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#544]
**Describe the bug**
We see that our users don't republish the app but keep rejecting the archival every week.
Is it possible to implement one of the following improvements?
- Republish the app/flow automatically for the user using 
![image](https://user-images.githubusercontent.com/5990852/97294162-ec3e8200-184d-11eb-8d18-567b6cd8315e.png)

- When they reject for archival, don't resend the archival approval every week but for example every 6 months? The schedule of that flows should be kept on every week, but by using an additional condition not sending the approval for archival every week anymore...

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit/governance
 - Version: Latests
 - App or Flow: Archival request flows for Apps and Flows archival

**Expected behavior**
After a user rejected archiving and didn't republish, don't send the archival mail every week again to the user.

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We don't want to re-publish for the user as this would negate the forcing function of making them question if they still need the app. We are adding a check to see if the app was launched though, so apps that are in use will no longer trigger archival (expect in ~1 month).

If you still want the re-publish when the user rejects, you could add a flow on your side which, on some time basis of your choosing, goes and republishes apps that have had their archival rejected. You can use the **_Admin | App Archive and Clean Up - Check Approvals and Archive_** flow as a basis for this for how to get those rejects. Note that you cant use a trigger off the approvals table due to product limitations though, and will need to just do a periodic sweep like we do in that flow. 

Thanks for using CoE!
