### ISSUE TITLE
[BUG]: Incorrect URL in email - Admin | Compliance detail request

### ISSUE THREAD

**Issue by aschauera** [microsoft/powerapps-tools#548]
**Describe the bug**
The URL sent to makers to provide compliance details is formatted incorrectly - the linked PowerApp (Developer Compliance center) cannot pick up URL paramenter and show details page for the app.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance
 - Version 1.70.6
 - Flow Admin | Compliance detail request
**To Reproduce**
1. Start Admin | Compliance details request for an app matching "broadly shared"
2. Open maker email
3. Click link to developer compliance center
4. Developer compliance center shows start page (not detail page)

**Expected behavior**
Compliance center shows the detail page of the app.

**Mitigation**
Change email text in flow action "Send an Email V2 in branch "Audit apps that are broadly shared - Yes"
Change URL: Replace "/" with "&" before parameter "appName"

  <li>Login to the <a href="@{variables('compliancePortalUrl')}**/**appName=@{items('Apply_to_each_App')?['admin_appid']}">Developer Compliance Center</a> and locate your app.</li>

**Comment by JeneferM-MSFT** [comment]
thanks we have this local fixed for next release

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
