### ISSUE TITLE
[BUG]: Archival of Power Automates created by End Users is not possible using CoE Governance Components

### ISSUE THREAD

**Issue by xeroOrex** [microsoft/powerapps-tools#554]
**Describe the bug**
When we try to archive Power Automates created by end users ( not the Admin Account which was used to configure CoE), it' s throwing 403 Forbidden error

**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance Solution
 - 1.24
 - Admin | Flow Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
1. Run the 'Admin | Flow Archive and Clean Up - Start Approval' flow
2. Click on the Approve button once you get the mail asking for the permission to archive
3. Wait for the 'flow Admin | Flow Archive and Clean Up - Check Approvals and Archive' to finish

**Expected behavior**
The flow should be archived and its body and connection references should be uploaded as JSON file inside the SharePoint site ( Archival site)

**Screenshots**
![image](https://user-images.githubusercontent.com/53090923/97887569-1ad9c280-1d50-11eb-8d74-2d012d5e45f5.png)

**Additional context**
Actions like **Get Flow** , **List Flow Owners** fail when they try to fetch details for Power Automates created by other users except the Admin Account. But even if we use **Get Flow as Admin** instead of **Get Flow** , we do not have the output "Flow Definitions" which is required to get the Flow Content

**Comment by JeneferM-MSFT** [comment]
Hello. Thanks for using CoE. 

We had been notified of this break by another customer and have it local fixed for the next release. Will hold this open for others until release.

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**NOTE ALSO:** The way that the archival system works has changes now. 
1) No longer backing up for the user:
In the past we would back up the apps and flows for the owners in a SP library, and then they would need to find those backups later, or reach out to the Power Platform admin for assistance in finding those backups. 
We received some feedback from customers that this is problematic, and a few product changes were made which make this less reliable. 
As a result, we have moved to a system in which the users will be responsible for backup of their apps and flows themselves for later use, in the event they change their minds. 

2) An environment variable _ProductionEnvironment_ was added. If set to "no", it will send all approvals to the admin instead of the end user for your dev and test installations.

3) Changing the criteria to flag for archival:
Apps will now check for both modified and launched dates. By default, if they have not been launched NOR modified in 6 months, they will flag for archival
Flows will now be flagged for archival if they are not in the stopped state, as well as not modified in the last 6 months. 

Thanks for using CoE, and helping make it great with your feedback.
