### ISSUE TITLE
[BUG]: How to avoid email notifications while deploying CoE Starter kit in the staging environments?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#558]
Hello!

We have CoE Starter Kit deployed in the "Dev" environment and planning to deploy in the fresh "Test" environment.

However, We need to know whether emails will be sent to users via CoE flows again even if they have received when CoE Starter Kit was deployed in the "Dev" environment?

On the other hand, "Turning" flows "On" triggers are generated based on the past events as well. More information is here - [https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Flow-Turn-Off-Turn-on-functionality/idi-p/385982 ](https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Flow-Turn-Off-Turn-on-functionality/idi-p/385982 )

Considering this, What strategy we can apply to avoid email notifications while managing CoE Starter kit in the different environments without generating repeated existing user's email notifications via CoE Flows from the different environments?

Thank you in advance!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Can you explain what you are trying to do within the Dev environment? 
If you really want to use and test the flows that email users in dev, you would need to modify the flows themselves to email someone else.

**Comment by JeneferM-MSFT** [comment]
As an update, we were updating these flows anyway, and per your feedback I have added an envt variable that can be used. 

Current POR is that it will be an env var called ProductionEnvironment with default value of True. 
For any dev environments you set up you can mark this to false, and then we will assign the approvals / emails to the admin instead. 

We will release this with the next update to the CoE 

Thanks for the feedback!

**Comment by dips23** [comment]
Hello Jenefer,

Appreciate considering the feedback! 

Regarding your previous question, In the Dev environment, We are trying to update CoE flows email actions/recurrence configuration etc and check when and how each flow are being sent and update as per the org need.Therefor, we have to consider the same CoE solution into other staging environments as per the how solutions deployment works in the Power Platform.

However by deploying the same solution from dev to test environment, CoE flows will be triggered again and we do not know whether it will send the emails to App/Flow Owners again because "Turn On" functionality of the flow suggest the same? If that happens - We want to avoid it because we do not want end users to receive the same email repeatedly! 

Can you please help on things to consider for the deployment stratagy on Dev-Test-Prod environments to avoid sending repeated emails with current CoE starter kit we have in the Dev Environment? 

Thank you for your understanding!

Regards,
Dipti

**Comment by dips23** [comment]
Hi Jenefer,

Thank you for your response, I think changing the email action to someone else would save the duplications of emails to end user, however I have further noticed two points:

**1.** CoE Solutions currently deployed into the Dev environment can not be exported as they are managed solution - considering this, Is CoE kit deployment should have staging environments like "test/dev" ? Or it should be deployed only in the single environment per organization?
**2.**  If we deploy Microsoft's version of CoE kit in each staging environment ( dev,test,prod) - How the CoE data would be managed as each environment will start with fresh data? should we migrate CoE data with some sort of automation? - Does it again indicates that CoE must be deployed in the single environment per organization?

Can you please help clarifying further on this and suggest the best practices for CoE Starter kit deployment in the staging environments?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Here are the instructions for [extending the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/setup#extending-the-starter-kit)

Please let me know if you have questions after reviewing.
Thanks for using CoE

**Comment by dips23** [comment]
Hi Jenefer,

Thank you for the link, that helps a lot and I understood as follows:

**1.** If Microsoft Version's CoE kit needs to be extended, then create new custom solution ( e.g. "Custom CoE Kit" ) and add all "customized" components into New custom solution  "Custom CoE Kit".

**2.** When new updates arrive, make sure that in the existing Microsoft Version's CoE kit solutions have no "Solution Layers", if there are any, then remove it, so that new updates get applied without any problem during "Upgrade" process.

However, when we do "Upgrade" - How to upgrade "Custom CoE Kit" solution that contains custom components derived from the previous version of CoE Kit? Do we have to create another custom solution again to incorporate with the latest changes of the CoE Kit? 

Looking forward to hearing from you soon!

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
On Q1) 
You will upgrade the managed solution from us and it will overwrite the old managed solution you got from us, it will not touch your new unmanaged solution.
From there, you can save-as whichever flows/apps you want, and import them to your unmanaged solution, and redo your changes on top.

On Q2)  with the new env var we are shipping, you will just have those set to isProd=no, and the end users will not be prompted for archival.

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**NOTE ALSO:** The way that the archival system works has changes now. 
1) No longer backing up for the user:
In the past we would back up the apps and flows for the owners in a SP library, and then they would need to find those backups later, or reach out to the Power Platform admin for assistance in finding those backups. 
We received some feedback from customers that this is problematic, and a few product changes were made which make this less reliable. 
As a result, we have moved to a system in which the users will be responsible for backup of their apps and flows themselves for later use, in the event they change their minds. 

2) An environment variable _ProductionEnvironment_ was added. If set to "no", it will send all approvals to the admin instead of the end user for your dev and test installations.

3) Changing the criteria to flag for archival:
Apps will now check for both modified and launched dates. By default, if they have not been launched NOR modified in 6 months, they will flag for archival
Flows will now be flagged for archival if they are not in the stopped state, as well as not modified in the last 6 months. 

Thanks for using CoE, and helping make it great with your feedback.
