### ISSUE TITLE
[BUG]: NoPermissionsForEmbeddedApplications when getting SharePoint List Apps

### ISSUE THREAD

**Issue by winterscar** [microsoft/powerapps-tools#561]
**Describe the bug**
The Admin | Sync Template v2 (Apps) flow fails with the following error when trying to process SharePoint list apps.

The failure occurs in the "Check if App Shared with Tennant" group, when running the Get App Role Assignments as Admin step.

![image](https://user-images.githubusercontent.com/11340175/98535970-e5b4ff00-227e-11eb-91df-b9eef638219b.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.70.6
 - App or Flow: 'Call  Admin | Sync Template v2 (Apps)'

**To Reproduce**
1. Create a SharePoint list app
2. Run Admin | Sync Template v2 (Apps) for the default environment
3. The flow does not run successfully for the default environment.

**Expected behavior**
No errors.

**Comment by JeneferM-MSFT** [comment]
Hello. This issue is known #543 and fixed locally for the next release. 
thanks for using hte CoE!

**Comment by JeneferM-MSFT** [comment]
Since that's a long thread, pasting the workaround here if you want to local fix before we re-release:

![image](https://user-images.githubusercontent.com/62659043/98552851-d10f4180-2253-11eb-9fdc-8fcd2b00592c.png)
Where the left side of that condition is : `items('Apply_to_each_App')?['properties']?['embeddedApp']?['type']`

**Comment by winterscar** [comment]
Thanks Jenefer! I just changed the whole "Check if app shared with tennant" step to ignore failures for now, and I'll install the next update when it comes around. 

Recon we can close this...

**Comment by JeneferM-MSFT** [comment]
Let's keep it open so I can dupe to this instead if more come in, the original thread is just too noisy :)

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
