### ISSUE TITLE
[BUG]: There are missing dependencies. Install the following solutions before installing this one: "Active"

### ISSUE THREAD

**Issue by MSPFE2019** [microsoft/powerapps-tools#564]
Error while import CenterofExcellenceAuditComponents_1_24_managed.zip. The core solution has been imported and installed with no issues.
![image](https://user-images.githubusercontent.com/57810061/98845923-fc408f00-2413-11eb-8ec5-47519c9a8bfc.png)

**Comment by JeneferM-MSFT** [comment]
Hi there. Thanks for using the COE. I believe what is missing is the Connection References. 
Can you please confirm that by going to Solution History > select the failure 
You should see text like this, let me know what it says
![image](https://user-images.githubusercontent.com/62659043/98848183-2ee38b00-2406-11eb-910f-9f99b4f1717a.png)


If it is the connection references, these are instantiated via the Core solution, and were new in 70_6.  
Do you have that version of Core installed? And if so, can you please validate that you see the connection references:
![image](https://user-images.githubusercontent.com/62659043/98848524-b3360e00-2406-11eb-979e-45b1f469d5c2.png)

**Comment by WouterF** [comment]
I had the same issue in the past when importing another solution than the CoE with connection references.
The error "There are missing dependencies. Install the following solutions before installing this one: "Active" occurs because you have connection references in the "Default Solution" under "Solutions".
Probably you didn't do it, but for some reason the product group creates connection references in the "Default Solution".
When importing, you get this error because these connection references are in another solution package than you try to import.
For me the issues was to recreate the connection references. But I'm not sure if is the way to go for the CoE.
Anyway, I think the product group still has work to do to make the connection references better.

**Comment by JeneferM-MSFT** [comment]
A new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

Please install Core and then try your case for the audit components again.

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
