### ISSUE TITLE
Question around flow CLEANUP flow marking default environment as deleted

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#565]
Hi there,

We just updated to CoE starter kit version 1.70.6.  We're not using the audit log capability just yet, so I activated the flow "CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)" to pull in who apps (and flows) are shared with.  

For this question, I'm focusing on apps.  While it completes successfully, it doesn't appear to be pulling in data for all apps.  There are multiple apps in my tenant where I know they are shared, but the Power Platform User Role entity has no data for those apps.  The apps show in other CoE entities, and are not deleted, orphaned, etc.

Am I using this flow for the wrong purpose, or is this a real problem?
Thank you,
Christi

**Comment by JeneferM-MSFT** [comment]
Hello, can you please let know how many apps you have in your tenant currently? 
I ask because we have recently found several customers gong beyond the limits count wise our solution could handle. And an update next week will allow for a larger number.

**Comment by osbornecc** [comment]
Sure, including SharePoint form apps we have just over 300 across our tenant.

**Comment by JeneferM-MSFT** [comment]
OK, then you are not impacted by the capacity limit. 
Were the apps for which you dont have the shared-with info all SP-apps? We cannot access the information for SP Embedded Apps as that information is not exposed in the Power Platform connectors.

**Comment by osbornecc** [comment]
The apps that don't have the shared-with info are Canvas apps.  I did see the other issues regarding failures accessing SP-apps that will be resolved (we get the same failures).

Does the latest Power Platform Admin View app filter out SP apps?  The "All Apps" app count in there does not match what we actually have.  If that needs to be a different issue, let me know.

Thanks.

**Comment by JeneferM-MSFT** [comment]
OK so you have 300 apps, and how many environments do you have? 
I'm wondering, if its a low number of environments, if you can ensure that they all correctly go down the "yes" path of this condition. And if you can also walk through both of the loops shown to see if you see any failures. Some may be caught and I want to be sure they are correctly caught. 
![image](https://user-images.githubusercontent.com/62659043/99008505-291ba180-24fb-11eb-842b-16dbd546e113.png)

The failures you mention should not occur in this flow. This flow does a filter out of the SP apps as you can see in the image above. If you see them in this flow please let me know. 

Regarding the PP Admin View, you may have an off count due to not collecting the SP apps (as you state). I suggest you install the upgrade that comes next week and if you still see the issue, post a separate bug for us.

**Comment by osbornecc** [comment]
Technically we have 11 environments but only 10 get pulled into CoE (one is a proof of concept Dynamics environment so I ignore it).  The 10 that need to be in CoE are in CoE and the flow loops look good.

Do we just need to wait until the upgrade and see what happens then?
Thanks!

**Comment by osbornecc** [comment]
Good morning.  I know this entry is unrelated to this particular issue, but I wanted to make a note and didn't think it needed its own issue just yet.

Over the weekend, the CoE flows gave my "default" environment a "deleted on" date (the is deleted flag is still No).  This ended up causing all my apps in "default" to be marked as deleted except for one.  

Because I didn't want users of the reports getting confused, I deleted the solution and will wait until the next CoE toolkit update.  If it still happens, I'll be sure to enter a new issue.  But I just wanted it written down so I wouldn't forget :-)

Thank you.

**Comment by JeneferM-MSFT** [comment]
A new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

It does contain a fix for the issue you identified at the end of this thread. 

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.

**Comment by osbornecc** [comment]
Hi Jenefer,
I'm running the flow from Core Components 1.71 now.  If all goes well, I'll close this issue.
Thank you,
Christi

**Comment by JeneferM-MSFT** [comment]
Wonderful. For the last issue you mention, it will be the (Check Deleted) flow which should repair the issue.

**Comment by osbornecc** [comment]
Good morning,
First, I haven't run the Check Deleted flow yet since I'm still verifying the data from the other flows.

Which brings me to second.  We're in GCC so we cannot use the Audit Log piece at this time (at least that's how I interpret the documentation) so we're committed to using the "CLEANUP" flows from CoE.  The "Power Apps User Shared With" flow finished successfully, and this time I see more rows in the Power Platform User Role entity than before yesterday's CoE update.  

However, it is still not the full list of "shared with" for apps. (right now it only shows apps and not flows but that's OK for now).  

For example, I have an app that appears in Power Apps App and is marked as having one "groups shared with."  It has a valid owner, and the app is not deleted.  That app ID cannot be found in Power Platform User Role at all.  Even the record that should hold the owner is not there.  

I'm not sure if it's just timing out or skipping apps.  I still need to look at the flow output.  But I do know that multiple apps in my tenant have this same situation.

Thoughts?
Sorry I don't have better news!
Christi

**Comment by JeneferM-MSFT** [comment]
The order that you activate and run the sync flows is actually important for how quickly your inventory will normalize. 
Here is our recommended order:
1.	Turn on: CLEANUP - Admin | Sync Template v2 (Check Deleted)
2.	Wait until it finishes before you turn on any other flows.
3.	Ensure the Sync Template flows are already turned on for the following object types:
Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, PVA, RPA
4.	Turn on Admin | Sync Template v2. When it completes, turn it back off.
5.	This will cause the flows for the objects listed in step 3 to run. Wait until all of these complete.
6.	Turn back on Admin | Sync Template v2.
7.	Turn on the rest of the flows listed in the solution


Note that this order will be listed in the next shipping version of documentation under [Activate the sync template flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows)

One of the fixes in this upgrade is an increase in pagination for listing things like apps and flows, so you may have been missing apps before. 
My suggestion is to please enable the flows in the order described above, and then see what state we are in. 

Looking forward to hearing results!

**Comment by osbornecc** [comment]
Because the flows get turned on when the solution imports, and I'd had them running for a few days, I did what I could to force the order above.  Things look really weird now, but I'll give it a couple of days to work itself out.

Thanks!

**Comment by JeneferM-MSFT** [comment]
Flows should import turned off now with a product change, so I'll follow up too.

**Comment by osbornecc** [comment]
Hi Jenefer,
Well, this just gets weirder.  I started to look at the data this morning and discovered that overnight the (Check Deleted) decided to delete my Default environment.  All data related to that environment is now gone from CoE.

I ended up finding that out because the (Power Apps User Shared With) failed trying to update an App ID in the Power Platform User Role table that no longer existed.

Would this end up being a new issue, then?
Thanks,
Christi

**Comment by JeneferM-MSFT** [comment]
It sounds like you did not receive our update to Check Deleted, or there is some product bug in play. 

Can you please go to the solutions layer of Check Deleted. 
![image](https://user-images.githubusercontent.com/62659043/99561544-eaaf3800-297b-11eb-9c0a-60a4add5ec56.png)

If you see an unmanaged layer like this, then you did not receive the update. (unless you know that you intentionally edited the flow since you upgradedL
![image](https://user-images.githubusercontent.com/62659043/99561410-c4899800-297b-11eb-9308-b6484e4c3bf8.png)

Another way to check would be to open that flow and see if you have these "Unmark x as Deleted" scopes:
![image](https://user-images.githubusercontent.com/62659043/99561823-3cf05900-297c-11eb-881e-8c19ea56cef5.png)

**Comment by osbornecc** [comment]
Hi Jenefer,

Hmmm, being in GCC it looks like I don't have the Solution Layers option

![image](https://user-images.githubusercontent.com/50427725/99564277-154ec000-297f-11eb-9b9d-ff8ab514c8f8.png)

But, I do see that the Check Deleted does have the steps you were looking for.

![image](https://user-images.githubusercontent.com/50427725/99564315-226baf00-297f-11eb-8e67-7889fbfb83e4.png)

I did edit the flow, but only to change the Recurrence day/time.  Since we can't use the Audit Log connector in GCC, I wanted it to run daily after the "main" sync flows run.

Let me know if I need to create a new issue for the Check Deleted.
Thanks,
Christi

**Comment by JeneferM-MSFT** [comment]
Can you edit the "Get Environments" action at the top of (Check Deleted) to have this API Version, and rerun? 
![image](https://user-images.githubusercontent.com/62659043/99570265-880f6980-2986-11eb-82e4-569ba35a3969.png)

**Comment by osbornecc** [comment]
OK, I got my Default environment back into the data then I updated the (Check Deleted) so it shows the API version 2020-09-01.  It said 2020-06-01.  I'm now going to wait for everything to run on schedule and see what happens in the morning.

On a related note, should I make the same change to the (Power Apps User Shared With) "List Environments as Admin" step?
![image](https://user-images.githubusercontent.com/50427725/99572459-8bf0bb00-2989-11eb-855a-8bbd6e43f1c7.png)

Thanks again for all your help with this!  When the data is there, it is very useful.

**Comment by JeneferM-MSFT** [comment]
Let's wait and see what happens as is. I anticipate the other changes made in this version to resolve it for you.

**Comment by osbornecc** [comment]
Hi Jenefer,
Sad news.  The flows deleted my Default environment from the tables again last night.

**Comment by JeneferM-MSFT** [comment]
1) I'm wondering if GCC uses different namings for default. 
Can you plesae tell me, when you go look in the Environments table in the CoE, what does your Name field show for the default envt? Here is what mine says but with an actual GUID
Default-22222222-1111-22222-1111-222222222222

And then if you do a Get environment as Admin on default, is the same string returned?
![image](https://user-images.githubusercontent.com/62659043/99688101-44763780-2a3a-11eb-9a8b-a9449c6c1ca1.png)
![image](https://user-images.githubusercontent.com/62659043/99688276-76879980-2a3a-11eb-8d30-a4406bb672fd.png)


2) Can you see if, in the run of (Check Deleted), did it actually mark your default as not deleted as shown here? 
![image](https://user-images.githubusercontent.com/62659043/99688498-bbabcb80-2a3a-11eb-906f-d1e8abddeee0.png)

**Comment by osbornecc** [comment]
OK, I'm going to do this in two comments since there are a few large screenshots.

First, the question about how the Default environment appears.  I reran Admin | Sync Template v2 so I could get the environment back into CoE (the "delete from CoE" environment variable is set to yes and I can't change it.  Not a big deal)

Environments table:
![image](https://user-images.githubusercontent.com/50427725/99696669-cf0f6480-2a43-11eb-9461-e438f06ea0de.png)

Get Environment as Admin results
![image](https://user-images.githubusercontent.com/50427725/99696834-fb2ae580-2a43-11eb-8117-24059da06595.png)
![image](https://user-images.githubusercontent.com/50427725/99696908-10a00f80-2a44-11eb-9236-39618ba54e84.png)

**Comment by osbornecc** [comment]
For the (Check Deleted) flow run, I think I may have found the problem.

The flow gets all values from the Environment table.  Then it gets all the values from "Get Environments (Preview)."  It compares the "name" value from Get Environments with the "Environment" field from the table.  I'm guessing this is "admin_environmentid".

If my guesses are correct, the two ID's don't match so it decides the environment is deleted.

Here are snippets of data from the outputs of last night's run:

**Environments Entity results for Default environment**
"ItemInternalId": "xxxx-xxxxx-xxxx-xxxdeeb",
"admin_environmentname": "Default-xxxx-xxxxx-xxxx-xxxdeeb",
"**admin_environmentid**": "xxxx-xxxxx-xxxx-xxxdeeb",
 "admin_displayname": "xxxxxxxx (default)",

**Environments results from Get Environments for Default environment**
 "**name**": "Default-xxxx-xxxxx-xxxx-xxxdeeb",
 "displayName": "xxxxxxxx (default)",

**Comment by JeneferM-MSFT** [comment]
You are correct. Thank you so much for debugging. We will release an update tomorrow with this fixed.

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released just now: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback. 

Given the size of this issue's correspondance, I will close with the (Check Deleted) issue fixed. 
Please post a new issue should any of the other issues you discussed above still repro.
