### ISSUE TITLE
Last Launched is not being populated

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#568]
[last_launched.docx](https://github.com/microsoft/powerapps-tools/files/5539490/last_launched.docx)

**Comment by manuelap-msft** [comment]
Hello,

I just saw this issue now - this GitHub repo is used for many different projects, with different teams responsible for different projects. As such, the CoE team only monitors issues that have the "coestarterkit" label which you can automatically get by selecting "CoE Starter Kit Issue" when raising a new issue
image
![image](https://user-images.githubusercontent.com/55705669/100329558-bbc14380-2fc5-11eb-8bf6-8cb26fcc8093.png)


This ensures the right people get a notification about this issue.

Are you still experiencing issues here?

**Comment by ssquiresusps** [comment]
Thanks for following up.  Yes still having issue documented.

**Comment by manuelap-msft** [comment]
Have you configured the Audit Log solution and are those flows running successfully? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog 

Last Launched Date is populated via the Audit Log connector.

**Comment by ssquiresusps** [comment]
Yes please see run history showing successful runs.

**Comment by manuelap-msft** [comment]
If your tenant is large with lots of activity, you might have to work on the time interval in which logs are retrieved - there is a limit on how many log actions can be retrieved in one go, and maybe your interval is set to high so it's missing the Power Apps events.

Edit the Admin | Sync Audit Logs flow to update the time interval at which the log clusters should be retrieved. Try setting this to 1 Hour instead
![image](https://user-images.githubusercontent.com/55705669/100461501-c9a7bf00-30c0-11eb-939c-2f6a03adda1d.png)

Please also note that the Audit Logs can't look into the past - they will run and look at last launched dates from the time they are set up, so some last launched dates might be empty if the app has not been launched since the Audit Log has been set up.

**Comment by ssquiresusps** [comment]
I took a screen shot -- could you review.   I have a feeling these are not right.

**Comment by manuelap-msft** [comment]
If you added your screenshot here, I'm afraid it didn't come through

**Comment by ssquiresusps** [comment]
![Capture](https://user-images.githubusercontent.com/71052204/100471183-58a3df80-309f-11eb-9ab1-de5785b5c5ed.JPG)

**Comment by manuelap-msft** [comment]
Yes, that looks correct to me!

**Comment by ssquiresusps** [comment]
Should the re-occurrence be set to run every hour versus every day?

**Comment by manuelap-msft** [comment]
No, it will run once a day, gathering your Audit Log events in 1hr chunks and then processes them.

**Comment by ssquiresusps** [comment]
Ok thanks you.  Will see what happens over the weekend.  Appreciate you help very much!!!

**Comment by ssquiresusps** [comment]
Last launched date is still not populating,  Do you have any other idea?  This issue sure has been a stinker to try to resolve.  Appreciate any help you're able to provide.

![lastlaunched1](https://user-images.githubusercontent.com/71052204/100753757-d1f94600-33af-11eb-95e3-44bac5582d22.JPG)
![lastlaunched2](https://user-images.githubusercontent.com/71052204/100753772-d6256380-33af-11eb-9254-53670e828faa.JPG)

**Comment by JeneferM-MSFT** [comment]
Hello. We are not repro-ing this issue so I'd like to ask you a few more questions

**Audit Log Access**
Did you validate that the user who's credentials are running your CoE has access to the [audit logs](https://protection.office.com/unifiedauditlog)? 

**Look at the audit log table**
Can you please go to the table for the audit log data and see if values are present:
    Go to Data > Tables > Select All from the top-right filter, open audit logs and export the data
![image](https://user-images.githubusercontent.com/62659043/100760714-e8e76a80-33a6-11eb-9b67-95234f071aef.png)
Open the resulting Excel table and see when was the last record entered (Creation Time)

**Force the issue**
I presume you did this already, but can you please let me know. 
Have you launched canvas apps yourself since enabling the audit logs? And if so, did you look for them specifically in the report?

**Comment by ssquiresusps** [comment]
****Did you validate that the user who's credentials are running your CoE has access to the audit logs? -->  Yes
****Can you please go to the table for the audit log data and see if values are present:
 Go to Data > Tables > Select All from the top-right filter, open audit logs and export the data ->  The audit log table does not exist.
***Have you launched canvas apps yourself since enabling the audit logs? And if so, did you look for them specifically in the report? -->  Yes

**Comment by ssquiresusps** [comment]
Would it be possible to set up a team or zoom call to help resolve issues?

**Comment by JeneferM-MSFT** [comment]
Sorry but no, we cannot do support calls with our GitHub users. We must do the debugging here. 
Can you please let me know, do you see the other tables from the CoE in the list? Ex : Flow Action Detail
My guess is that you did not filter to show all tables, as shown here. 
![image](https://user-images.githubusercontent.com/62659043/101045252-ffbbc780-3534-11eb-9990-2c33c74353d4.png)

**Comment by ssquiresusps** [comment]
Yes I wasn't showing all tables.

The table appears to be empty and I'm not presented with the export data option.

**Comment by ssquiresusps** [comment]
![Capture](https://user-images.githubusercontent.com/71052204/101053284-37366e00-354d-11eb-8155-b6927ca271ee.JPG)

**Comment by ssquiresusps** [comment]
![Capture](https://user-images.githubusercontent.com/71052204/101053422-6351ef00-354d-11eb-9807-902e6b9967b4.JPG)

**Comment by JeneferM-MSFT** [comment]
Do you see the drop down where it says "Active Audit Logs"? Can you please drop that down and chose "All columns"?
If it is still empty when you show all columns, can you please see if you can view the data in other table in the CoE, like the "Environments" table?

**Comment by ssquiresusps** [comment]
[Tables.docx](https://github.com/microsoft/powerapps-tools/files/5638682/Tables.docx)

Unable to see data in audit table -- able to see data in environments table.

**Comment by ssquiresusps** [comment]
[Tables.docx](https://github.com/microsoft/powerapps-tools/files/5638798/Tables.docx)

**Comment by ssquiresusps** [comment]
![Capture](https://user-images.githubusercontent.com/71052204/101408817-94f6ed00-38a2-11eb-8e0b-bb7a746f492d.JPG)


Please let me know if you need anything else.   Thanks for your help!

**Comment by ssquiresusps** [comment]
I guess somehow I closed this issues despite it never resolving it.   Any further ideas?

**Comment by ssquiresusps** [comment]
I guess somehow I closed this issues despite it never resolving it.   Any further ideas?

**Comment by JeneferM-MSFT** [comment]
Can you please go in to a successful run for the Child flow and find a write that succeeded? 

Click through **_Apply to each Audit Cluster_** until you get to one that has at least one LaunchPowerApp operation. 
![image](https://user-images.githubusercontent.com/62659043/102365563-8a0c1e80-3f6c-11eb-99e9-3307a9ba41e5.png)

Open the switch statement below and validate that these two actions succeeded
![image](https://user-images.githubusercontent.com/62659043/102365675-aa3bdd80-3f6c-11eb-99d0-a3d2fde8a7bc.png)

**Comment by ssquiresusps** [comment]
[last_launched12_16.docx](https://github.com/microsoft/powerapps-tools/files/5704394/last_launched12_16.docx)

**Comment by JeneferM-MSFT** [comment]
if you expand the search date, do you see launches?

**Comment by JeneferM-MSFT** [comment]
Never mind I see your comment about knowing that launches should be in there. This issue is unrelated to our toolkit then, you are not getting the writes to the data source at all. You will need to work with your support person to resolve this as its not an issue with our tooling. 

I will send them a note too, 

Thanks and best of luck resolving.
