### ISSUE TITLE
[BUG]: Environments not returning Microsoft Teams Type

### ISSUE THREAD

**Issue by achaganti** [microsoft/powerapps-tools#576]
Core Components is not listing the type as MicrosoftTeams, rather its showing them as "Not specified". I am using the version 1.71.1 which is the latest one. 
![tempsnip](https://user-images.githubusercontent.com/34516164/99394593-26f38180-2905-11eb-9e8a-5fca683e8224.png)

**Comment by manuelap-msft** [comment]
If you navigate to the Core Components solution and edit the Admin | Sync Template v2, scroll down a bit to the Get Environments action (it's within a scope). Click on "Show advanced options". Does that show 2020-09-01 as the API Version or something lower? Earlier versions of the API don't return Microsoft Teams as the Environment Type, but instead return NotSpecified which is what leads me to think that this is the issue as in your BI screenshot I can see NotSpecified.
![image](https://user-images.githubusercontent.com/55705669/99395130-e598ad00-28d7-11eb-9c65-e35fb4a10165.png)

Did you upgrade to 1.71 or was 1.71 the first and clean install you made?

**Comment by manuelap-msft** [comment]
It looks like the upgrade to 1.71 didn't take due to an unmanaged layer in your solution.

Please open the Core components solution, and for every flow/app go to the solution layers and remove it:
![image](https://user-images.githubusercontent.com/55705669/99419122-a9734580-28f3-11eb-820b-9c68a7239f14.png)

![image](https://user-images.githubusercontent.com/55705669/99419134-ad06cc80-28f3-11eb-871e-ad5625004d9e.png)

Please note, if you have made customizations to any flows that you want to keep you will need to take a copy of the flow first. You will have to do this step for every app and flow in the starter kit. All the ones that contain unmanaged layers will cause issues during the upgrade.

Once you have removed all unmanaged layers, you can do the upgrade again and it should then succeed.

**Comment by JeneferM-MSFT** [comment]
This has been removed for now. Please be sure to [install updates as described in the documentation.](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
Thanks for using CoE
