### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Flows) runs never ending v1.71.1

### ISSUE THREAD

**Issue by mpinuel** [microsoft/powerapps-tools#589]
**Describe the bug**
I installed v1.71.1 of Core Solutions and first execution of "Admin | Sync Template v2 (Flows)" never ending during more than 5 days for the Default environment

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.71.1
 - Admin | Sync Template v2 (Flows)

**To Reproduce**
1. First runs on new v1.71.1 installation
2. We have 15 environments, so Sync Flows has 15 executions (one per environment). The default environment process has been running for almost 6 days, so today we decided to cancel the execution:
![image](https://user-images.githubusercontent.com/32450895/99992582-cf4a8f80-2db6-11eb-8ec0-0a4b11a3e627.png)

3. The flow has been running for 6 days in the Apply to each Flow action (we have 2966 Flows in the Default environment):
![image](https://user-images.githubusercontent.com/32450895/99993015-61529800-2db7-11eb-8193-072299be2d67.png)

4. We have monitored the data that is filled in the CDS table "Environment" each day, and 3 days ago we have 1856 Flows updated in the Default environment. Today, after 6 days of execution, we have 1981 Flows. No flow information has been updated in the last 8 hours (we still have 1981 flows) so we decided to cancel the execution:
![image](https://user-images.githubusercontent.com/32450895/99993636-403e7700-2db8-11eb-9d98-97c85a1ea485.png)

**Expected behavior**
We expect that the first execution will require a lot of time, since it has to update the data of all the flows of each environment, but it seems too long and in addition every day of execution it updates less data (even in the las hours it had stopped).

**Additional context**
We have found similar issues #545 and #497 but seem to be solved in v1.70.6 and we have a more updated version.

Thanks!
Regards,
Miguel.

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid that the issues you are seeing are due to throttling, and we cannot make the flows run faster than they are given your tenant size. 

You have two options
1) Assign a per-flow license to this flow, in which case you will not be throttled in the initial data load.
2) Re-trigger the main sync flow and wait the long time it will take to fill the CoE with your list of flows.

Note that for #2 above:
- [Guidance](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows) is to trigger the main sync flow and then turn it off until all objects finish. This will prevent you from calling multiple times for the same flow. 
- If you wait a few days to do this, your accounts throttle will not be hit anymore and it will be faster at first
- You have already put in ~1/2 the flows so those will not be as time consuming
