### ISSUE TITLE
Table with name 'msdyn_flow_approvalresponses' does not exist

### ISSUE THREAD

**Issue by jameswh3** [microsoft/powerapps-tools#60]
After importing the **Center of Excellence - Compliance and Report Components** solution and opening the "Admin | App Archive and Clean Up - Check Approvals and Archive" workflow, I receive an error stating that the 'msdyn_flow_approvalresponses' table does not exist.

![CoEWorkflowError](https://user-images.githubusercontent.com/4581067/73594093-71b82000-44d0-11ea-8c75-a5a5128447b6.png)

I looked at the entities in the solution, and I only see two:
![CoEAuditEntities](https://user-images.githubusercontent.com/4581067/73594107-9a401a00-44d0-11ea-9d2d-e9f4365c1d4a.png)

**Comment by manuelap-msft** [comment]
Step 5 of the Audit and Report Components Setup instructions in the manual point out how to initialize the Approval entities
https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/CoE%20Starter%20Kit%20-%20Documentation%20and%20Setup%20Instructions.pdf

**Comment by AhmadiRamin** [comment]
Hi @manuelap-msft , we are facing the same issue, can you refer me to the new documentation which I should look into to solve this problem?

**Comment by manuelap-msft** [comment]
Here is the documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-entities-in-your-environment

**Comment by VinnyDyn** [comment]
Hi @manuelap-msft , the same problem... appear the COE solutions haven't the entity.

Error:
![image](https://user-images.githubusercontent.com/36446614/107442679-466e0500-6b16-11eb-9dfd-f29cb03d4079.png)

Log:
![image](https://user-images.githubusercontent.com/36446614/107442597-21799200-6b16-11eb-9586-126d83bc4486.png)

**Comment by manuelap-msft** [comment]
Please follow these steps to initialize Flow Approvals in your environment https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment

If you have never used Approvals in the environment, the Flow Approvals tables are not yet available. Previously this could be done after solution import, looks like due to a product change this is now required prior to solution import. We will update our documentation accordingly.
