### ISSUE TITLE
[BUG]: Error importing core components -  Import failed: An item with the same key has already been added.

### ISSUE THREAD

**Issue by ndocosta** [microsoft/powerapps-tools#605]
When importing the solution Core Components I receive the following error:

Solution "Center of Excellence - Core Components" failed to import: Import failed: An item with the same key has already been added.

![image](https://user-images.githubusercontent.com/12910235/100372748-a2d68380-3001-11eb-8a4d-6505811f58b4.png)

Log File:
[Center of Excellence - Core Components_import.txt](https://github.com/microsoft/powerapps-tools/files/5604018/Center.of.Excellence.-.Core.Components_import.txt)

I've tested this on two tenants, brand new environments and got the error on both.

Thanks.
Best regards.

**Comment by ndocosta** [comment]
The only way I was able to import it, was without specifying the two environment variables during import.
Is this the expected behavior?

**Comment by manuelap-msft** [comment]
As per https://github.com/microsoft/powerapps-tools/issues/566 this a product bug at the moment. You can raise a support ticket, where a support engineer will disable a value called: FCB.SolutionSimplificationImportMigration.EnvironmentVariableValue.

**Comment by manuelap-msft** [comment]
Closing out duplicate issue.

**Comment by djmc90** [comment]
If you are having trouble setting the environment values because of the work-around, you can do so in the .ZIP file before you import the Solution.

Using the CoE Core Componenets as an example, to set the 2 variables:

1) Unzip the CoE Starter Kit
2) Open up CenterofExcellenceCoreComponents_1_71_7_managed
3) Open up customizations.xml
4) Search for Power Automate environment variable and set (i.e. for EMEA env):      <DefaultValue>https://emea.flow.microsoft.com/manage/environments/</DefaultValue>
5) Search for Admin eMail and set it's default value accordingly like above
6) Save your changes and replace the existing file in the ZIP.

Now import this ZIP file and your values will be set on import.

I was getting the error, so i had to import in classic mode as above

Hope it helps.
