### ISSUE TITLE
Developer Compliance Center App Error

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#610]
**Describe the bug**
When a user launches the Developer compliance center app they receive an error message for not having permission to view data. I have attached the screenshot of the error message below. 

User has the following role

- Approvals User, Common Data Service User, Environment Maker, PowerApps Custom Entity User Role 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance Component
 - Version - 1.25
 - App - Developer Compliance Center

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/100652175-834a9e00-3314-11eb-86ce-7ca7e986e622.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. You need to give the users permissions to the CDS in order for them to see the data. 
Please see our documentation on this in [the setup instructions.](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#developer-compliance-center)

**Comment by lrarbin** [comment]
Hello JeneferM,
I'm not sure if I can comment on a Closed Ticket. But I'm getting the same error.
`Error is: You don't have permission to view this data. Server Response: Archive Approvals failed: Principal user (Id=12de8525-fddb-ea11-a815-000d3a25cd55, type=8, roleCount=3, privilegeCount=0, accessMode=0), is missing prvReadadmin_ArchiveApproval privilege (Id=50c35816-4fad-4fcd-973f-fc4c43ce5f39) on OTC=10143 for entity 'admin_archiveapproval'. context.Caller=12de8525-fddb-ea11-a815-000d3a25cd55`

I've looked at the Role Settings in Dataverse for 'Power Platform Maker SR'. Under 'Custom Entities' the 'Archive Approval' Entity has 'None Selected' for all the permission options.

I've updated my environment with these updates, but it doesn't seem to have fixed anything.
CenterofExcellenceAuditComponents_1_38_managed
CenterofExcellenceAuditLogs_1_3_5_managed
CenterofExcellenceCoreComponents_1_89_managed
CenterofExcellenceNurtureComponents_1_24_managed
Thanks
Laurence

**Comment by JeneferM-MSFT** [comment]
Hello, yes a maker doesn't need access to that table in order to participate in approvals process. The product itself allows for participation in approvals without envt access, and then the flows in gov run in the context of your admin so they are the ones that need access to the Archival Table. 

And I dont know why that app would require access to the table, though I didnt create it so I will need to reach out to the maker. 

Can you please create a new issue for that?
Here is my suggested title, and the I can figure out which way to go with the fix. 
- The Developer Compliance Center App has dependency on Archive Approval table, but the Maker SR does not have access.

**Comment by JeneferM-MSFT** [comment]
ok i see the spot they use the table in the app, so my fix will be to the SR. 
but if you can please still post this as a separate issue, then I will hold until the fix ships and we can track that it is resolved once done.
