### ISSUE TITLE
[Issue] - Non MS connectors avaliable in the Org

### ISSUE THREAD

**Issue by luisportillov** [microsoft/powerapps-tools#614]
Our general comunication and collaboration platform is no form MS (Gmail/Confluence),

We wnat to use the kit, but when importing the solution, it is mandatory to use the conectors to Exchange and Sharepoint. 

Is there a way to install the solution without using the MS connectors?

**Comment by manuelap-msft** [comment]
Hello, I am assuming your issue is regarding the CoE Starter kit? This GitHub repo is used for many different projects so when raising a new issue or questions it's best to select from the list of projects here to make sure the issue is routed to the correct team.
![image](https://user-images.githubusercontent.com/55705669/101181557-ee61e080-3644-11eb-8a90-149a1cac1d0f.png)

If you are talking about the CoE starter kit, then this has a dependency on Office 365 being used.

**Comment by luisportillov** [comment]
Thanks, will have the selection in mind for futures post.

Yes it was regarding the COE starter Kit. Thanks, understood the dependency. Just wanted to see if on the roadmap is something planned to have a more open connectivity outside O365.

Thanks.
