### ISSUE TITLE
[BUG]: issue title Cannot turn Admin | Sync Template v2 on after Importing Core Components 1.71.7

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#618]
**Describe the bug**
Cannot turn Admin | Sync Template v2 on after Importing Core Components 1.71.7

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.71.7
 - App or Flow Sync Template (v2)

**To Reproduce**
1. Import Solution CenterofExcellenceCoreCo,p[onents_1_17_7_managed
2. Select Solution
3. Scroll down to '....' of Admin | Sync Template V2 and click on '...'
4. click Turn on

**Expected behavior**
I expect the flow to Turn On

**Screenshots**
![CoEError](https://user-images.githubusercontent.com/8484048/101175803-878cf900-363d-11eb-8c2d-89a13665ab9a.png)

**Additional context**
I have tried on two different Tenants - same failure - I have taken the CoE environment out of all DLPs in both Tenants I have a Per User Flow Licence.

**Comment by JeneferM-MSFT** [comment]
Hello. You must have the environment is a conflicting DLP policy in order to see this error. 
I suggest you to please re-look at the [pre-reqs list](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites), and then if you believe you have the correct DLP policy in place, you may have hit a product bug. 

Sorry we cannot assist with those at this time, you'll need to contact support. 
Thank you
