### ISSUE TITLE
[BUG]: Get PowerApp Owner Profile for new fails

### ISSUE THREAD

**Issue by dluzzi01** [microsoft/powerapps-tools#621]
**Describe the bug**
Get PowerApp Owner Profile for new fails with error 
Error from token exchange: Connection asia-001/logicflows/guid@https://asia-001.azure-apim.net/ is not allowed to access connection asia-001/office365users/guid"

**Component (please tell us which flow or app you are experiencing issues with):**
 - 
![powerapps_fail](https://user-images.githubusercontent.com/59740101/101523964-4fe0c280-3957-11eb-9e9f-2b2d40f12f23.PNG)
Solution Core
 - Version 1.70.6
 - Flow Sync Template (v2) Apps

I think the issue may be thats its trying to add an app with an owner that no longer exists in AD and is failing.  I cannot find the owner by the guid in the error.

**Comment by JeneferM-MSFT** [comment]
We had a bug a while ago (#537 ) in that the switch following this call did not have the correct configure-run-after settings. 
Can you please check? 
![image](https://user-images.githubusercontent.com/62659043/101647558-b7e1e800-39ed-11eb-9031-1dd644c66b7d.png)
![image](https://user-images.githubusercontent.com/62659043/101647610-c8925e00-39ed-11eb-8a2b-099b4f65f739.png)

If you dont have that setting then either you have not installed with that fix, or the install did not overwrite the flow. 
Note that technique for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) has changed and you need to delete any unmanaged layers in flows in order to receive updates. 

Thanks for using CoE

**Comment by dluzzi01** [comment]
Thanks I will apply this change.

So when we go to delete the unmanaged layer does that remove any manual changes?  After upgrading do we have to reapply the changes?

I did not make copies of the flows and just used the original ones in the solutions.  I remember earlier that was the recommended approach but when we redeployed the CoE I saw that that documentation did not mention it so I just used the ones in the solutions.


[cid:image001.png@01D6CE15.E2C2A350]
David Luzzi | Administrator, IT Service | Tel: +15195615376 | Mobile: +15192599845
[cid:image002.png@01D6CE15.E2C2A350]

**Comment by JeneferM-MSFT** [comment]
`So when we go to delete the unmanaged layer does that remove any manual changes? After upgrading do we have to reapply the changes?`

yes and yes. Power Automate does not support any merging of changes yet and so this is the only way to recieve updates. 
It is the recommendation to make any intentional changes in a copy of the flow or the solution as a whole.
[Extending the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/setup#extending-the-starter-kit)

**Comment by JeneferM-MSFT** [comment]
closing out issues with no further action
