### ISSUE TITLE
Issue:  Admin | Sync Template v2 (Apps) flow failing for some apps

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#642]
Ever since upgrading to Core solution 1.71.7, I've been receiving daily email alerts from CoE stating that various flows are having errors.  The errors are occurring for various apps (but not all) within the same environment as well as multiple environments. A sample of my email notification is shown below:

![image](https://user-images.githubusercontent.com/52799471/102538415-d9884280-4071-11eb-8f2d-918384e35058.png)

Here is the run history from last night's Admin | Sync Template v2 (Apps) flow.

![image](https://user-images.githubusercontent.com/52799471/102538534-03416980-4072-11eb-86e3-6ba9757ba520.png)

Here's the detail info for the flow I have highlighted in the first screenshot.  I have spot checked a few of these and each indicate 'Cannot read property 'push' of undefined'.

![image](https://user-images.githubusercontent.com/52799471/102538749-4c91b900-4072-11eb-8058-3f4ab3255a77.png)

**Comment by JeneferM-MSFT** [comment]
Hello your upgrade seems to have failed as you do not have the correct actions in your flow. Your flows are actually quite old looking.
Please note the process of [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) has changed. You have to delete unmanaged layers in order to get the update. Please follow the instructions on [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) and try again.  

Once successful you will have this condition in many of your flows, including this one. 
![image](https://user-images.githubusercontent.com/62659043/102542196-47c70800-4066-11eb-8010-e9c66a64b384.png)

If you still have issues after update please post. 
Thanks for using CoE

**Comment by dchrist27** [comment]
Hi….

I reapplied the 1.71.7 update to core components after removing the unmanaged layers.  The Admin | Sync Template v2 (Apps) flow ran last night and I noticed 2 failures.  Here’s one of the failure flows.

[cid:image001.jpg@01D6D865.F1D912C0]
