### ISSUE TITLE
Flow Connectors in CoE starterKit - not up to date as added after move from full inventory by default

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/powerapps-tools#705]
**Describe the bug**
In the Power Platform Admin view (model driven app) when I open a flow I don't see all of the connectors that are used in the flow, I can only see SharePoint but there is more connector used. Also in a solution in one environment there are 5 different flows, I can see 3 of them in this model driven app but I can not see parent and child flow. I had to put all the flows into a solution because of this parent and child flows. Why I can't see these flows?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version 1.78]
 - App or Flow: PowerPlatform admin view

In Power BI report all dashboards with the information about flow connections are not correct. I can not filter makers by flow connector used (I can do this for app connectors) I can not pick a flow to see the connectors and I can  not pick a connector to see all flows using this connector.

**Comment by JeneferM-MSFT** [comment]
Can you please share pictures of what you see? Note that pictures need added here in Github you cannot add via a reply in email

**Comment by MarinaHadzi** [comment]
For example, when I open my flow I see these connectors: 
![image](https://user-images.githubusercontent.com/71693895/105045538-50956a00-5a68-11eb-829c-cc3b1e1e8adf.png)

IN the PowerPlatform Admin view I can't see Microsoft Teams connector:
![image](https://user-images.githubusercontent.com/71693895/105045882-acf88980-5a68-11eb-9391-09dd57ec05c9.png)

Is it because these flows are in a solution? But then again why is SharePoint connector displayed and Teams is not.


Also Cloud flow maker insights show this:
![image](https://user-images.githubusercontent.com/71693895/105046658-a9b1cd80-5a69-11eb-8d58-1c3a0410e6d4.png)
When I click on myself this is shown:
![image](https://user-images.githubusercontent.com/71693895/105046761-c77f3280-5a69-11eb-9b10-8ced75147ed8.png)

Non of the cloud flow dashboards correctly filter information about makers connectors.

**Comment by JeneferM-MSFT** [comment]
This second set of images (associated with makers) is tracked in #703. That report will likely be cut. 
We will track just the first issue here as a result. 

This works for me locally so can you please confirm:
- do you see this issue generally or just with this flow / this teams connector?
- if you wait for the sync flows to run again, does it still repro? (perhaps the connection was added after the sync flows ran)
- if just teams, if you go to the Connectors view instead and see what apps/flows are associated with Teams?

**Comment by MarinaHadzi** [comment]
Regarding the Teams: 
I can see it in another flow that isn't in a solution but for a lot of flows (that are in solutions) I can not see this connector.
The connector is added prior sync flow run.
If I go in connectors view and I can only see flow that is outside the solution connected with Teams, I can not see other flows inside a solution connected with Teams.

**Comment by JeneferM-MSFT** [comment]
OK I validated that this is not about solutions. I see the flow + connection properly in sync for both solution and non-solution flows. 

My guess is that you have is an incomplete inventory because we no longer update flows that are not new or have not changed since the last run. And the work to note solution connections is new

Two options to fix this:
1) Turn the env variable full inventory to yes if your tenant is small or you can buy a set of per-flow licenses. This will have your inventory always up to date
1) Run the clean up flow for connections "CLEANUP - Admin | Sync Template v3 (Connection Status)"

I suggest the second option.
Information about long running flows here: [Limitations - long running flows](https://docs.microsoft.com/power-platform/guidance/coe/limitations#long-running-flows)
You may run in to this known bug during the cleanup run #669

**Comment by MarinaHadzi** [comment]
I can see Teams connector now.

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thanks for using CoE
