### ISSUE TITLE
[BUG]: Custom Connectors not in Connection Reference table

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#710]
Hi there,
I commented on the original issue (#611) but figured I'd go ahead and open a new one.

Anyway, we're on Core Components 1.78.  I need to see which apps use Custom Connectors, but they are missing in the Connection Reference table.  Here's what I found.

In the simplest way, you can see a delivered connector has Apps associated with it
![image](https://user-images.githubusercontent.com/50427725/105195923-f5a75580-5aef-11eb-9775-131221b9aea2.png)

But a custom connector that I know is used in at least one app shows nothing
![image](https://user-images.githubusercontent.com/50427725/105196055-12dc2400-5af0-11eb-8f56-18c37303c203.png)

Because I'm creating reports, I was in Power BI so I could see the raw data.  In the Connectors table, my custom connector had no data for the "admin_id" field.  Delivered connectors do.
![image](https://user-images.githubusercontent.com/50427725/105196292-533ba200-5af0-11eb-9240-e89e868ce194.png)

I'm not sure if that's the issue or not, but I modified the Admin | Sync Template v3 (Custom Connectors) flow to include the ID.
![image](https://user-images.githubusercontent.com/50427725/105196701-bf1e0a80-5af0-11eb-9341-af242066a3a7.png)
![image](https://user-images.githubusercontent.com/50427725/105196863-ea085e80-5af0-11eb-8475-57433f9e0029.png)
![image](https://user-images.githubusercontent.com/50427725/105196882-ed9be580-5af0-11eb-926f-e4dbd47305c2.png)

Now Custom Connectors show data in the admin_id field
![image](https://user-images.githubusercontent.com/50427725/105196955-ff7d8880-5af0-11eb-87f8-e6f59d0c40fa.png)

But there is still something preventing Custom Connectors from appearing in the Connection References table.  The Admin | Sync Template v3 (Apps) flow does select admin_id from Connectors
![image](https://user-images.githubusercontent.com/50427725/105197310-52574000-5af1-11eb-8d6d-716ec598129f.png)

For existing apps (which all of mine are), I wonder if the problem is in the highlighted section below.
![image](https://user-images.githubusercontent.com/50427725/105197596-a104da00-5af1-11eb-8eeb-7bb4ebb77c6c.png)

I haven't had a chance to try a new app with a custom connector, but I will do that this morning.
Also, this appears to be the same for Flows but we don't have as many using Custom Connectors yet.
Thanks.

**Comment by osbornecc** [comment]
Ahh, it works for apps that do not already exist in CoE (new apps).  I created the below app in one of our environments and then ran the CoE flows.  The connection reference shows up!

![image](https://user-images.githubusercontent.com/50427725/105202820-38b8f700-5af7-11eb-8130-7b439b80558c.png)

![image](https://user-images.githubusercontent.com/50427725/105202883-4a9a9a00-5af7-11eb-8702-2bc0c37d339e.png)

So there is something wonky with the "already exists in CoE" section of Admin | Sync Template v3 (Apps) I believe.
Thanks.

**Comment by JeneferM-MSFT** [comment]
Hello. Yes we had to move away from doing full inventories recently due to changes in the way Power Automate throttles api calls. So where we used to walk the entire tenant in order to update properties for all flows, apps, bots, etc. We now only update an app, flow, etc when it is new or has been updated. 

This works for most situations, but occasionally, if we have made an addition or fix to the sync flows, you wont be able to see the benefits of that fix on unchanged objects until you run a full inventory.

Such is the case here. In order to do a full inventory:

1) Set the environment variable for **_full inventory_** to "Yes"
1) Run the sync flows
1) Turn the variable back to "No" in order to avoid long running nature of the suite.

See here for how to set up [update environment variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables)

Thanks for using CoE
