### ISSUE TITLE
Request: If PowerApps/Power Automate Owner is not found copy file to SharePoint

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#712]
**Describe the bug**
Hi @JeneferM-MSFT 

recently I faced an issue where the power automates creator left the organization and his team was still using the power automate since the creator did not found it came to admin and the admin deleted the flow because the creator was not found. in the early CoE kit, there was a feature where if the owner is not found it and the admin approves it before it gets deleted it will store a copy of Power Automate/PowerApps to the SharePoint site so we can retrieve it back. Can the CoE team add this feature back? 

Also, another question is - Are Power Automate flagged to be deleted when the flow creator is terminated, even if there are other owners of the Power Automate who are still active employees? 

I had this discussion with @topness-msft. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid we cannot add that feature back, we removed the support due to some product changes. We are no longer able, at this time, to reliably restore flows created by other people programmatically. This is because of the way that connections are now stored. We have given the product team feedback and if the capability returns we will add this back in. 

The new archival flows instruct owners to back up their own flows before the system deletes them (if deletion approved). 
People who have user permission should also be able to create a backup. 
We do not automatically mark flows for deletion if they are orphaned.
