### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#720]
**Describe the bug**
When the flow is executed, all the audit logs are not uploaded.
We noticed that the "Audit Log Content List" action only returns 600 items.
Is there a limit and how can I get all the elements ?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Audit Logs
 - Version 1.3.2
 - Flow [Child] Admin | Sync Logs

**Screenshots**

![image](https://user-images.githubusercontent.com/34766578/105473165-1365ed80-5c9d-11eb-965c-4c4ec97a4bc9.png)

**Comment by manuelap-msft** [comment]
Yes, there is a limit in how much the Office 365 Management API returns and it does not handle pagination. You will have to edit the Admin | Sync Audit Logs flow to update the time interval at which the log clusters should be retrieved. The default is set to one-day intervals, you might have to change the interval to 1 Hour to get all the logs in your organisation.

**Comment by orauch-a** [comment]
I have already tried this.
But the child flow failed with a 429 error on the "GetContentDetails" action.

**Comment by JeneferM-MSFT** [comment]
Can you please try to update the retry policy to see if that resolves for you? 
Please see example from our [limitations page](https://docs.microsoft.com/power-platform/guidance/coe/limitations#timeouts-in-the-admin--sync-template-v3)

**Comment by JeneferM-MSFT** [comment]
Hello again. We are getting ready to release the Feb update and hoped to make the fix suggested above if it helps you. 
Were you able to make those changes and see if it resolved your issue?

**Comment by orauch-a** [comment]
Sorry for the delay. I will be check this this week. And I will make you feedback

**Comment by JeneferM-MSFT** [comment]
Hello. We went ahead and made this change in the release today. 

Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!

**Comment by jagibe** [comment]
Hello,

I'm sorry for reopen this thread, but i'm having the similar problems.

The organization i'm working on is very large and the number of logs is high.

I'm trying to adjust the parameters in order to get the flow work correctly, but I haven't achieved it.

Pagination errors were thrown until I set the flow to get logs every 30 min in intervals of 2 mins. With this configuration, I still see Rate limit errors of Management Activity Api. 

Later, I configured the grade of parallelism of foreach loops to only execute 1 child flow at a time, and 20 in Apply to each cluster (Child flow).
With this configuration at certain hours of the day, the number of logs is so high and it seems that is doing some retries, overlapping the executions and causing the flows to fail at some point.


If you have some recommendations or you can guide me for achieve that for larger organizations, please I would really appreciate that.

Thank you

Thank you
