### ISSUE TITLE
Page limitation issue in all Sync flows

### ISSUE THREAD

**Issue by jainmilan002** [microsoft/powerapps-tools#725]
Hello Team,

I am getting above error for every flow while I try to Turn on and then i need to edit every flow and correct error for every action which is bit annoying and time consuming as well.

"The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'."

**Component (CenterofExcellenceCoreComponents_1_78_managed):**
 - Solution [Core]
 - Version [1.78]
 - App or Flow [all syn flows)]

**To Reproduce**
1. Go to 'all sync flow'
2. Click on 'Turn On'
3. See error

**Comment by JeneferM-MSFT** [comment]
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)
