### ISSUE TITLE
[BUG]: COE tool kit not updating actual data  from Power platform 

### ISSUE THREAD

**Issue by suresh8696** [microsoft/powerapps-tools#743]
**COE tool kit not updating actual data  from Power platform **

Power platform admincenter data was not matching with the COE toolkit data in front end.  We have exported Flows information using PowerShell it is showing 9000+. But in COE tool kit it is showing as 5000+. Is there any issue with COE Kit  to fetch the data from admin center

**Comment by JeneferM-MSFT** [comment]
Hello. I am afraid we will need more information in order to assist. 
Can you please see what version of Core you are using? 
![image](https://user-images.githubusercontent.com/62659043/106611585-ffcc4980-651c-11eb-81bb-f4d297e5d754.png)

We did have a reliability issue with an old connector (that is being deprecated) and so had to make new versions of the sync flows. I had a few customers impacted in their flow count in particular with that old connector. The naming in the new version is like this
![image](https://user-images.githubusercontent.com/62659043/106612141-a6184f00-651d-11eb-97d4-3ed1bf253e59.png)

**Comment by JeneferM-MSFT** [comment]
Hi there. Checking in to see if you can please check in on your core version.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without followups.
