### ISSUE TITLE
[BUG]: Power Platform Maker SR/User SR Permissions

### ISSUE THREAD

**Issue by fredericklin** [microsoft/powerapps-tools#757]
**Describe the bug**
For both the Power Platform Maker SR and Power Platform User SR security roles, the Audit Logs, COE Connection Reference, and COE Settings table permissions are not set correctly.  A user that is assigned to this role will not be able to load the Admin View Power App or the Power BI dashboard.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.78
 - App or Flow: Admin View and Power BI report

**To Reproduce**
1. Add user to the Basic User security role
2. Add user to the Power Platform User SR security role
3. As the user, access the Power Platform Admin View app or load the Power BI report

**Expected behavior**
It should load without any errors.

**Screenshots**
N/A

**Additional context**
If the user is a member of the Power Platform Admin SR security role, it works fine.

**Comment by JeneferM-MSFT** [comment]
Hello. I did find a couple spots in the SR's where new tables were missed, and those have been updated for the next release thanks to you posting this issue. 

However, please note the following about our reports:

- Power BI dashboard - we do not use direct query and so your report, as published to powerbi.com should open fine for anyone with the link, they should not need permissions to the back end in order to load as the report will just show the last refreshed version. 
 
- Admin View Power App - this model driven app is intended only for the Admin persona.

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
