### ISSUE TITLE
[BUG]: issue Developer Compliance Center App Error. Archive Approvals permissions lacking

### ISSUE THREAD

**Issue by lrarbin** [microsoft/powerapps-tools#778]
**Describe the bug**
When a user launches the Developer compliance center app they receive an error message.
`You don't have permission to view this data. Server Response: Archive Approvals failed: Principal user (Id=7ae2150b-b7d0-ea11-a812-000d3a25ce3c, type=8, roleCount=4, privilegeCount=0, accessMode=0), is missing prvReadadmin_ArchiveApproval privilege (Id=50c35816-4fad-4fcd-973f-fc4c43ce5f39) on OTC=10143 for entity 'admin_archiveapproval'. context.Caller=7ae2150b-b7d0-ea11-a812-000d3a25ce3c`

User has the following roles
Basic User, Power Platform User SR, Power Platform Maker SR via an AAD Group

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - CenterofExcellenceAuditComponents
 - Version 1.38
 - App or Flow - Developer compliance center

**To Reproduce**
1. launch the Developer compliance center app

**Expected behavior**
No errors

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/8376969/108365739-750f6e00-71ef-11eb-9b2d-eeaddfc70ce5.png)

User Settings:
![image](https://user-images.githubusercontent.com/8376969/108365677-61640780-71ef-11eb-8624-e18b7eea4a99.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
I just went to find the dupe for this since I already fixed it and then realized this was the bug I asked you to post to track :)
So thank you for posting! I have this local fixed and it will ship with the March update.

**Comment by lrarbin** [comment]
Hello Jenefer,
I think the problem is lack of permissions, but not being the developer, I don't know what the 'should' be. So for example I can fix this by adding:
![image](https://user-images.githubusercontent.com/8376969/108372285-9031ac00-71f6-11eb-991d-298b1e398f21.png)

When I've tested before there are then others with a similar issue. But I'm guessing it could be that the Canvas App itself could be at fault, i.e. the Maker Role trying to use something it shouldn't have access to.

I'm guessing is there a workaround till March?
Thanks
Laurence

**Comment by JeneferM-MSFT** [comment]
You are correct, the fix is to grant the Maker security role full read access to that table, so only the read column in your picture (2nd column I think) would be green, the rest empty.

Basically when we add tables to the CoE, or features from existing tables in to new apps, we don't always remember that the permissions need to also be updated, and of course we work from the admin persona and not maker. Hence the bug. 

We try to only ship monthly, and hence we will ship this in the March update, at the beginning of March. 

We do have a few other fixes in the security roles coming with the March release (see #757 ) so if you still see issues with the March release, please post them and we will fix. 

Thanks for helping make CoE great!

**Comment by lrarbin** [comment]
Thanks, setting that Permission change has fixed the issue for me.
Laurence

**Comment by JeneferM-MSFT** [comment]
Wonderful news. I will keep this issue open until we ship, for others to see.

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
