### ISSUE TITLE
[BUG]: DLP Editor V2 Impact Analysis

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#779]
**Describe the bug**
Some connectors which are not lockable through PPAC but using DLP Editor V2 allowed to block those connectors. I have attached the image below. Also when we block a connector in the existing DLP policy it does not show us any impact analysis on how many apps or power automate will get affected. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.89
 - App - DLP Editor V2

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/108389004-37094e80-71dd-11eb-8721-eaaf4a71d140.png)

![image](https://user-images.githubusercontent.com/75992078/108389031-3ec8f300-71dd-11eb-9382-2450d6971089.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Thank you! Unfortunately the DLP editor has to store a list of non-blockable connectors in the app because the connectors itself don't let us know if they are blockable. We went with the list from this documentation https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#list-of-connectors-that-cant-be-blocked - looks like there's a few others that are missing in the documentation. We will take a look and update the DLP editor for the next release. However, if you try to block a connector that is not blockable via the DLP Editor, this will not work (I think the Save operation would fail).

What do you mean by "we block a connector in the existing DLP policy it does not show us any impact analysis on how many apps or power automate will get affected"? Are you changing an existing policy and expecting apps to be impacted, but are not seeing that?

**Comment by AkashPatel136** [comment]
Are you changing an existing policy and expecting apps to be impacted, but are not seeing that? - Yes, Modifying the existing policy but do not see any apps or flow to be impacted by the changes.

**Comment by manuelap-msft** [comment]
And you are expecting the policy change to cause a conflict? E.g. you know that in the environments of the policy you have apps/flows that will be impacted?

**Comment by AkashPatel136** [comment]
Yes, I have a few flows and apps which can be impacted.

**Comment by manuelap-msft** [comment]
I'm looking into this at the moment, it looks like there could be delegation issues impacting this. Will provide an update by the end of the week

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
