### ISSUE TITLE
[BUG]: CoE upgradation issue

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#783]
**Describe the bug**
We installed CoE on November at an earlier version. Then two weeks back it was updated to new version. The only thing which we did was import the solution and install it as an update. So we can see the new flows (marked as v3) inside the solution and from history it looks like it's running successfully. On the other hand the old v2 flows which we saved earlier and activated are also running. As per the old documentation and CoE video series (https://www.youtube.com/watch?v=L8gKjeE5GR4&list=PLi9EhCY4z99W5kzaPK1np6sv6AzMQDsXG&index=2) we have saved all the sync template flows and then activated them. Can that be the issue why those v2 flows are still showing up outside the solution?

Can you please suggest what should be done? Should we disable v2 flows and keep v3 flows enabled? Or was there any issue with our upgrade?

**Comment by JeneferM-MSFT** [comment]
Hello. With the creation of the Connection References product feature, you no longer need to create copies of flows to use them. You now instantiate the connections once at solution install instead of at each step as in the painful past. We will be remaking the videos to match. 

You should disable and delete the old v2 flows, and you can keep the v3 flows in place now, making [installing udpates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in the future easier

**Comment by RamitK** [comment]
@JeneferM-MSFT Thanks so much! This clears all of my doubts.

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thanks for using CoE!
