### ISSUE TITLE
[BUG]Audit Log Component Child Flow #429 Error

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#798]
**Describe the bug**
In the [Child] Admin | Sync Logs , Fails due to an error **Rate limit is exceeded. Try again in 1 seconds.** 
CoE Audit Log Components
Version from 20.04.20
[Child] Admin | Sync Logs

**Expected behavior**
No errors. Run History succeeded 

**Screenshots**
![image](https://user-images.githubusercontent.com/78148795/109819316-efada400-7c59-11eb-8369-4ceac5ec5b10.png)

**Additional context**
Can you please help me to resolve this issue at the earliest. Due to which Admin log flow
![Error](https://user-images.githubusercontent.com/78148795/109819958-9134f580-7c5a-11eb-8052-f7766e8ab9c8.png)
 is also failing

**Comment by JeneferM-MSFT** [comment]
Hello. Likely an upgrade alone will fix you as we added a filter since your install. 
Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

If after install you still see this problem, you can edit the cadence of the flow as described in optional steps 10-11 of the [flow part of the solution setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow).

Thanks for using CoE.

**Comment by ApoorvaKantale** [comment]
Hi,

Thank you for the reply

Now we are getting the below error. When we try to run the child audit log.

It is really urgent can you please help us to fix this issue

**Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_admin-5foffice-20365-20management-20api-5f656d4006af872ade","shared_commondataservice_1","shared_commondataservice_2"]' with invoker runtime source.**
