### ISSUE TITLE
[BUG]: Set App Permissions Canvas App

### ISSUE THREAD

**Issue by davidvansickle** [microsoft/powerapps-tools#805]
<img width="463" alt="coeError" src="https://user-images.githubusercontent.com/9801374/110000548-0a732d80-7cd9-11eb-952d-5658af82f6e4.png">
**Describe the bug**
When assigning permissions, the following errors pops up.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.98
 - App or Flow Set App Permissions App

**To Reproduce**
1. Go to Environment
2. Select Apps
3. Click on Add Permssions
2. Search and Click on User 
3. Leave View as default
4. Click Save

**Expected behavior**
Permissions on all selected apps updated.

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

can you confirm that this app does indeed still exist in your tenant and environment or has it been deleted recently? 

The CoE Starter Kit has flows that run daily (Admin Sync Flows) that sync information about your tenant resources into Dataverse (CDS) tables. All the apps in the CoE Starter Kit are then based on those tables - because the sync only happens daily, sometimes the data could be out of date. So if the app got deleted recently it may still show up in this app but could still have been deleted from the environment.

A good way of tidying up the data in the CoE tables is to kick off the CLEANUP - Admin Sync Template v3 (Check Deleted) flow.

Hope that helps,
Manuela

**Comment by JeneferM-MSFT** [comment]
Closing out issues without further action
