### ISSUE TITLE
[BUG]: Power BI - Power Platform Admin Dashboard - Introduction - Cloud Flow Gurus - Broken Button

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#818]
**Describe the bug**
On the Power BI Power Platform Admin Dashboard, the very first page called Introduction the button labeled "Cloud Flow Gurus" does not work when pressed. It does not redirect to anything.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Setup power bi report
 - Version: 2021.03.03
 - App or Flow: PowerPlatformAdminDashboard

**To Reproduce**
1. Go to PowerPlatformAdminDashboard
2. Go to Introduction page.
3. Click on 'Cloud Flow Gurus'.

**Expected behavior**
Redirect to associated report

**Screenshots**
![20210310_CloudFlowGurus](https://user-images.githubusercontent.com/1613085/110705141-94c8ff00-81bb-11eb-8642-2a92abb96526.png)

**Additional context**
None.

**Comment by manuelap-msft** [comment]
Hello! Thanks for letting us know - we had to remove the Cloud Flow Gurus page (hopefully only temporarily) due to some issues with the relationships in our Power BI data model and are working hard on getting that back in. We missed to remove the button - we'll make sure to update accordingly with the next release (early April). Thank you for using the CoE!

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
