### ISSUE TITLE
Admin | Sync Audit Logs

### ISSUE THREAD

**Issue by AHmajid** [microsoft/powerapps-tools#826]
I get following error: Flow run failed.
![3](https://user-images.githubusercontent.com/80525833/110945400-ebf6dd00-833d-11eb-867c-cb7ef6b4c00d.PNG)

**Comment by manuelap-msft** [comment]
Hello,

the parent flow Admin | Sync Audit Logs fails because your Child flow fails which you've raised in a separate thread. This is not a different failure, but the failure is related to your child flow failing.

I'm closing this ticket, as we're working on the other ticket for the Child flow issue.

Thank you
Manuela
