### ISSUE TITLE
[BUG]: Inconsistent information about number of Flows using FileSystem connector in CoE

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#837]
**Inconsistent information about number of Flows using FileSystem connector in CoE**
As per Center of Excellence Power Platform Admin View App 'FileSystem' Connector used in 0 Flows 
As per PowerPlatform Admin center Analytics 'FileSystem' Connector used in 1 Flow 

Solution - Core
Version - 1.98

**Comment by JeneferM-MSFT** [comment]
Can you please share screenshots of the two spots you are seeing inconsistent data?

**Comment by apoorvakasbekar** [comment]
![image](https://user-images.githubusercontent.com/69908205/111170807-59b73900-85ca-11eb-8efd-bc11beabad09.png)

File System connector - No data available which indicates File System connector is not being used by any Flows 

![image](https://user-images.githubusercontent.com/69908205/111171003-8703e700-85ca-11eb-9d04-87ef9ce15d2a.png)

The second images is from the https://admin.powerplatform.microsoft.com/analytics/flow
It says File System connector is used by 1 Flow

**Comment by JeneferM-MSFT** [comment]
The hook up of flows and connectors was done after work to move to only update editted flows. 
You will need to do a full inventory run in order to get them all up to date. 
Please update the **FullInventory** environment variable to yes, trigger **Admin | Sync Template v3**, wait until that flow completes, and then set the variable back to no. 
To set environment variables please see [Update Environment Variables](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables)

Please see this detailed in our [limitations page](https://docs.microsoft.com/power-platform/guidance/coe/limitations#incomplete-inventory)

Thanks for using CoE!
