### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs - Missing Case Statement for "PowerAppPermissionEdited"

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#866]
**Describe the bug**
The Filter array command is pulling 4 conditions, 
@or(equals(item()?['Operation'], 'LaunchPowerApp'), equals(item()?['Operation'], 'DeletePowerApp'), equals(item()?['Operation'], 'DeleteFlow'), equals(item()?['Operation'], 'PowerAppPermissionEdited'))...

....but the switch/case statement is only logging 3. The logic doesn't appear to be doing anything with the PowerAppPermissionEdited data, there is no case statement and nothing in the default.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit Log Components
 - Version: 1.36
 - App or Flow: [Child] Admin | Sync Logs

**To Reproduce**
1. Go to '[Child] Admin | Sync Logs'
2. Edit the flow
3. Review the conditions in the filter array. There are 4.
4. Review the conditions in the switch/case commands.  There are 3.

**Expected behavior**
All conditions should be logging. Are we not logging PowerAppPermissionEdited by design?

**Screenshots**
![20210322_MIssingCaseStatement](https://user-images.githubusercontent.com/1613085/112063912-275c8d00-8b30-11eb-9035-2c43e13fcde2.png)

**Additional context**
Couldn't this be condensed into 1 flow? Not sure why there is a parent/child design with these 2 flows.

**Comment by manuelap-msft** [comment]
This is expected behaviour at the moment. Some of our customers wanted to be able to receive alerts for apps that are shared, but it wasn't broad enough feedback to implement this in the kit - we have therefore only prepared the flow to be able to act on this audit event. The CoE Starter Kit is a starting point for customers to implement their own admin and governance processes, and this is just one place where we provide a template only that can be modified.

The Parent Flow prepares time segments, and the Child Flow runs per time segment. The custom connector is limited in how many audit events it returns per call - for example, if you want to retrieve audit events on a daily basis, the parent flow prepares 1 hourly time segments (2021-03-21 09:00 to 2021-03-21 10:00) and calls the Child Flow 24 x for each time segment.

**Comment by robertcaretta** [comment]
@manuelap-msft  - Understood, thank you for clarifying. 

Regarding app sharing, we could actually use some tools or even some guidance on Flow sharing auditing/reporting. We'd like to have a "personal productivity" environment where sharing is not allowed. I started a discussion thread on this. 
https://github.com/microsoft/powerapps-tools/discussions/853
