### ISSUE TITLE
Admin | Sync Template v3 (Model Driven Apps) - See if app already in CoE failure

### ISSUE THREAD

**Issue by Grant-R** [microsoft/powerapps-tools#874]
I have multiple events of this module failing.  They've been happening since implementation, but I've never had a chance to go back and investigate, so they're not new apps, just never been in the CoE at all. 

I'm fairly certain that the error is caused by the users no longer being with the organisation and therefore the account doesn't exist. 

![image](https://user-images.githubusercontent.com/60246683/112586115-e671ba80-8e46-11eb-9df9-bf159435a666.png)

Should there be some form of error checking after the "Get PowerApp Owner" step?

**Comment by manuelap-msft** [comment]
Hello, 

this GitHub repo is used by many different projects, that are looked after by different teams. When you raise an issue, please ensure you select CoE Starter Kit issue to ensure your issue gets labelled and assigned correctly - otherwise we may miss it

![image](https://user-images.githubusercontent.com/55705669/113703994-7a5b4600-96d3-11eb-8bc4-a066b12717a0.png)


Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Hello what version of the toolkit are you using? In the past we had a bug where the configure-run-after of this switch statement was not catching failures. I assume that you are seeing that same thing and just need to upgrade.

**Comment by Grant-R** [comment]
Version is 1.89 I believe. Installed 12th Feb 2021.
When was the bug fixed?

**Comment by JeneferM-MSFT** [comment]
I'm not sure. But I know it is fixed in the version released now. We are shipping April this week if you'd like to wait to install. 
Thanks for using CoE
