### ISSUE TITLE
CLEANUP - Admin | Sync Template v3 (Check Deleted) Failed to activate component(s). Flow client error returned with status code "BadRequest" 

### ISSUE THREAD

**Issue by vynarim** [microsoft/powerapps-tools#878]
Trying to activate the flow "CLEANUP - Admin | Sync Template v3 (Check Deleted)" it fails and I have following message

Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'Get_Environments' of type 'OpenApiConnection

 - Solution : Core
 - Version: 1.98
 -  Flow 

1. Install CoE Core
2. Setup environment variables
3. Go to CoE core solution
4. Turn on "CLEANUP - Admin | Sync Template v3 (Check Deleted)"
5. 
![image](https://user-images.githubusercontent.com/20367460/112668342-b2a28f00-8e5e-11eb-86db-c6f3d0e3f1b7.png)

**Comment by JeneferM-MSFT** [comment]
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)

This is covered in #725
