### ISSUE TITLE
Flow archival

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#896]
Hi,

I was checking for an option to archive power automate flow same as app archival. Is there any option to archive a power automate flow same as power app?

**Comment by JeneferM-MSFT** [comment]
Hello we no longer archive apps nor flows for people at all due to changes in product. 
The new flows in this space just ask the object maker/owner to backup themselves if they would like to keep a copy. 
Thanks for using CoE

**Comment by Aparna-Mutalik** [comment]
Hi,

I still see archival option in governance solutions for both flows and apps. Is there any update in the solution which does not support archival? 
Can you please share any document link where it says app archival is no longer supported?

**Comment by JeneferM-MSFT** [comment]
If you update to the latest version of Gov, the flows are named with a V2 and now prompt the maker to do their own backup instead of doing it for them. 
![image](https://user-images.githubusercontent.com/62659043/113878534-eb076e80-9776-11eb-9864-54dee6531d2b.png)

The product still supports backing up apps, but the toolkit no longer does.
