### ISSUE TITLE
[BUG]: Power BI - Power Platform Admin Dashboard - Cloud Flows - Part of report doesn't show Team environment flows

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#898]
**Describe the bug**
Power BI Dashboard – “Cloud flows”, bottom left report does not display flows that are in Teams environments. Have tried different filters and resetting the filters. See screenshot.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 - App or Flow Power BI Dashboard

**To Reproduce**
1. Go to 'Power BI Dashboard'
2. Click on 'Cloud flows'
3. Select a Team environment. 
4. Part of the dashboard is reporting there are flows, and another part isn't. See screenshot

**Expected behavior**
Report should display flows from all environments.

**Screenshots**
![PowerBICloudFlows](https://user-images.githubusercontent.com/1613085/113938267-f59a2600-97bf-11eb-95a4-7303a0b8d176.png)

**Additional context**
NA

**Comment by JeneferM-MSFT** [comment]
Hello. Did you select that dot? If so it filters the date of creation. Did you have any flows made in teams on that day?

**Comment by manuelap-msft** [comment]
Hello,

can you try removing the # of actions column so only the below are selected for the table visual?
![image](https://user-images.githubusercontent.com/55705669/114016519-d56f7300-9862-11eb-8003-d5341279d437.png)

We had an issue with this visual in that if we didn't sync the # of actions for flows, the flows wouldn't show up there but this will be fixed in the next release. In the meantime, you can fix this yourself by removing the # of actions column from this table visual.

Thank you for using the CoE
Manuela

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
