### ISSUE TITLE
[BUG]: issue - Import of V2.0 of Core Components failed - Again

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#918]
**Describe the bug**
Import of Core Components failed.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0

**To Reproduce**
1.Import V2.0 of Core Components 

**Expected behavior**
I expected it to import without issues

**Screenshots**

Solution "Center of Excellence - Core Components" failed to import: Solution Upgrade action failed after import as holding. InnerException is: Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedflowpush_68e20, Id: 385bbf97-7698-46b3-aafb-2ca7aaf5391e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v3 (Sync Flow Errors), Id: 69c0077e-df40-eb11-a813-000d3a8f4ad6, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 .

This is the second environment this has happened. Issue #911

**Comment by manuelap-msft** [comment]
Hello,

thank you - this error message is much clearer and helpful then the XML file you provided with the last issue, so we may be able to help now!

We removed the Notifications connection reference from this version, as this connector is not available in GCC and GCC High environments. Our Admin | Sync Template v3 (Sync Flow Errors) no longer shows a dependency on this Notifications connector, but based on your error message this is causing a dependency issue for you. Can you select "see Solution Layers" for this flow and check if you have any unmanaged layers on this flow and remove them if needed following the steps described here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

![image](https://user-images.githubusercontent.com/55705669/114382074-d87ca300-9b83-11eb-8e98-28c85656239f.png)

**Comment by NPrice99** [comment]
It looks like the last update (v2.0 ?) – I am not sure I want to delete that one.

***@***.***D72FAA.1BF02DF0]

**Comment by JeneferM-MSFT** [comment]
Can you select "see Solution Layers" for this flow and check if you have any unmanaged layers on this flow and remove them if needed following the steps described here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

![image](https://user-images.githubusercontent.com/55705669/114382074-d87ca300-9b83-11eb-8e98-28c85656239f.png)

**Comment by NPrice99** [comment]
Hi Jenefer

Yes, I can select “See solution layers”.

Yes, there is an unmanged layer –
***@***.***D72FB4.64443790]


But when I click on delete “Remove Unmanaged Layer” Nothing happens.

I have tried to delete the solution completely it fails saying there are dependencies.

So I am stuck !

Regards

Nigel

**Comment by manuelap-msft** [comment]
Unfortunately images don't come through if you reply to issues via email. You would have to navigate to https://github.com/microsoft/powerapps-tools/issues/918 and reply from within GitHub. Thank you!

**Comment by JeneferM-MSFT** [comment]
Unmanaged layers need to be removed from your flows in order to receive updates to the toolkit.
Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

You will need to remove them from all your flows and then do the upgrade.

**Comment by NPrice99** [comment]
Hi Jenefer

I have tried removing them.

But nothing happens.

I have even tried deleteing the solution, but that fails because there are 30 dependencies.

So I am stuck.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Jenefer

Yes, I can select “See solution layers”.

Yes, there is an unmanged layer – 
 
https://user-images.githubusercontent.com/55705669/114382074-d87ca300-9b83-11eb-8e98-28c85656239f.png
![image](https://user-images.githubusercontent.com/8484048/114416538-b21d2e80-9ba8-11eb-8917-1972252c26df.png)


But when I click on delete “Remove Unmanaged Layer” Nothing happens.

I have tried to delete the solution completely it fails saying there are dependencies.

So I am stuck !

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
I'm afraid once you've started the process of deleting the solution then you are in a rather unpredictable state. You will likely need to start clean in a new envt.

**Comment by NPrice99** [comment]
Hi Jenefer

I am unable to create a new environment due to capacity limitations so I am have to find a way of getting this to work.

There must be a way of deleting the Solution.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Nigel the behaviors you are seeing, like the no-op when you try to delete managed layers indicate something is wrong with the solution at this time and I am unable to help you with that. Perhaps waiting a while, sometimes there are service issues that prevent things from working. Or you can look at all the dependencies and delete them manually and try the delete again. 

But I'm afraid you are outside of the scope of our ability to assist.

**Comment by manuelap-msft** [comment]
All our CoE solutions depend on Core - so if you have Audit Log, Governance or Nurture installed you would have to uninstall those first before being able to uninstall Core. 

I think what's blocking you from receiving upgrades are unmanaged layers in the Admin | Sync Template v3 (Sync Flow Errors) flow - can I suggest one more thing? When you select Import, can you change the default setting to **Update**
![image](https://user-images.githubusercontent.com/55705669/114426066-9702ec80-9bb1-11eb-8311-1a86485536de.png). Update (not recommended) This option replaces your solution with this version (from https://docs.microsoft.com/en-us/powerapps/maker/data-platform/update-solutions) and may work, although we have not tested this ourselves yet as we are not reproducing your issue on Upgrade (we have tried a few times ourselves now since you posted this issu)

If it doesn't, then I'm afraid like Jenefer said you are experiencing a product issue and I would suggest raising a support ticket. Unmanged layers should always be removable.

**Comment by NPrice99** [comment]
Hi Manuela
Unfortunately this did not work so I am having to hand craft the consumption part of Admin | Template Sync V3.
There must be a way of deleting a solution without deleting the whole environment. PowerShell perhaps ?

I can confirm that creating a new environment and installing v2.0 does work successfully.

But I cannot do that on my personal tenancy.

Regards

Nigel

**Comment by manuelap-msft** [comment]
Hello,

our upgrade paths are:

1) removing unmanaged layers from the flows and then upgrading
2) uninstalling the CoE Kit and then re-importing. this can be challenging due to components depending on each other. you may have to remove Nurture and Governance first before uninstalling Core.

It may be worth raising a support ticket here, I suspect a support engineer can help you with the upgrade as well.

Thank you
Manuela
