### ISSUE TITLE
[QUESTION]: Which flow updates the Environment Capacity Table

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#920]
**Describe the bug**
Which Flow updates the Environment Capacity Table as the table is empty

**Component (please tell us which flow or app you are experiencing issues with):**
 - SolutionCore
 - Version 2.0
 - Environments Capacity Table

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

the Admin | Sync Template v3 flow - the main flow that runs on a daily schedule and looks at environments also updates the capacity and add on information. You can find this a little bit buried in the "Get Environments and store them in the CoE CDS Entity" scope.

![image](https://user-images.githubusercontent.com/55705669/114404074-48e3ee00-9b9d-11eb-8763-628f2170b595.png)

**Comment by manuelap-msft** [comment]
If you don't have these steps, can you check if your flow has unmanaged layers in which case it may not have received the updates accordingly. 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

If you do have the steps, and are seeing the table as empty can you check the flow has run since your last upgrade and can you check the output of the "Get Environments" action at the top of this scope contains Add On and Capacity information.

Thank you
Manuela

**Comment by NPrice99** [comment]
Hi Manuela

I cannot remove the unmanaged layer as it is the active layer - ***@***.***D72FAF.C244CCB0]
Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Nigel is removing unmanaged layers working for you yet? Wondering if there was some service issue that might be resolved by now.

**Comment by NPrice99** [comment]
Hi @JeneferM-MSFT - Thanks for asking I have just tried it again and it is now working so I will try and upgrade again and let you know the result.
Thanks
Nigel

**Comment by NPrice99** [comment]
Hi @JeneferM-MSFT Yes it has just upgraded successfully - I can tell as the capacity steps are in Sync Template V3.  Thanks for letting me know the service issue has gone away.
Thanks
Nigel

**Comment by manuelap-msft** [comment]
Thanks for confirming it worked now! Closing this issue but please let us know if you face any other problems
