### ISSUE TITLE
[BUG]: Power Apps, Flows and tables not accessible after import (Dataverse for Teams)

### ISSUE THREAD

**Issue by tpertila** [microsoft/powerapps-tools#924]
**Describe the bug**
Imported Core Solution into new Dataverse for Teams environment. Import process was successfull, but after the import I can't access any new resources.

Apps
![image](https://user-images.githubusercontent.com/34052704/114500955-bb061280-9c31-11eb-8afe-f8d853620fd0.png)

Tables
![image](https://user-images.githubusercontent.com/34052704/114500989-c8230180-9c31-11eb-9c44-fa5feeca197f.png)

Apps can be found through PPAC, but flows are not shown even there.
![image](https://user-images.githubusercontent.com/34052704/114501033-dbce6800-9c31-11eb-96c5-a29f26163483.png)

Apps are also visible on Teams Power Apps home screen.

![image](https://user-images.githubusercontent.com/34052704/114510439-5baeff00-9c3f-11eb-9179-fa0f36656c8b.png)

But not when you browse all solution components.
![image](https://user-images.githubusercontent.com/34052704/114510537-78e3cd80-9c3f-11eb-94f1-736e101141df.png)

Did import once and waited 20 hours. Still not visible. I deleted the environment, made new one and import the core solution. Same end result.

**Comment by manuelap-msft** [comment]
Hello,

you will have to select Installed Apps to see apps and flows imported via a Solution, the Teams experience under See All will only show you what's developed in the environment:
![image](https://user-images.githubusercontent.com/55705669/114525114-bcd5d300-9c3d-11eb-9128-debe7770334b.png)

If you click See All on the solution you will see all components in the solution. You will again have to select cloud flows to see the cloud flows, they don't show up in the "All" view due to some product gaps.

Hope that helps,
Manuela

**Comment by tpertila** [comment]
Thanks!! Didn't know that.

**Comment by manuelap-msft** [comment]
We'll add it to our documentation! I don't think it's covered in the Power Apps for Teams docs either.
