### ISSUE TITLE
[BUG]: Governance component query

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#925]
**Describe the bug**
Hi, I need to confirm whether the latest version of the governance components supports archiving to a SharePoint site.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance
 - Version - 1.43
 - Admin | Archive and Clean Up v2 (Clean Up and Delete)

**To Reproduce**
N/A

**Expected behavior**
We've upgraded to a later version of the governance component and wanted to utilize the feature to archive unused apps to a SharePoint site. It seems the version of the flow no longer provides this option and instead deletes apps and flows directly. Was this feature previously available will there be an option in the future to make this feature available again?

**Screenshots**
N/A

**Comment by manuelap-msft** [comment]
Hello,

this feature was decommissioned in November last year, see our release notes:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/governance-1.25#archival-flows

Due to the complexity of restoring apps and flows and some product changes that made restoring for flows no longer possible, we have removed this feature and are currently not going to be able to make it available again.

Thank you for using the CoE
Manuela
