### ISSUE TITLE
[BUG]: Issue with upgrade of Core Components from 1.89 to 2.0

### ISSUE THREAD

**Issue by jefmeyer** [microsoft/powerapps-tools#927]
**Describe the bug**
We're receiving an error of:

Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_409c1, Id: 696e81c1-a969-4e22-bfef-2887b81f54c8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v2 (RPA), Id: 86f47022-b7f1-ea11-a815-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

When upgrading the Core Components from 1.89 to 2.0. Now our environment has 1.89 and 2.0 installed. The 1.89 version of the solution has an Office 365 Groups and Office 365 Users connection reference, but we're not seeing that in the 2.0 version.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - Version 1.89 upgrading to 2.0
 -  Admin | Sync Template v2 (RPA) 

**To Reproduce**
1. Import CoE Core Components 2.0 to an environment running CoE Core Components 1.89
2. Attempt upgrade

**Expected behavior**
Core Components should upgrade 1.89 to 2.0

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you have followed this process to remove any unmanaged layers before the upgrade:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by jefmeyer** [comment]
Thanks for the post.  We don't have any unmanaged layers.  Also, I'm not able to find the 'Admin | Sync Template v2 {RPA)' flow in either solution, but it's showing as a dependency:
![image](https://user-images.githubusercontent.com/22027681/114586533-61f6a880-9c4a-11eb-8a87-e6fba4285ba8.png)
When I click on the flow, I get the following:
![image](https://user-images.githubusercontent.com/22027681/114587099-f103c080-9c4a-11eb-9672-81aef72f4ec5.png)

**Comment by manuelap-msft** [comment]
That is strange, we recently updated all our sync flows and to indicate the update renamed all of them to v3.  You should only see a Admin | Sync Template **v3** (RPA) anymore and not a v2. Do you have both a v2 and v3 (RPA) flow?

Thank you
Manuela

**Comment by jefmeyer** [comment]
Should I see the Admin | Sync Template (RPA) flow in the Core Solution? I'm not seeing any RPA flow in the core solution.  Here's the 1.89 solution:
![image](https://user-images.githubusercontent.com/22027681/114589300-29a49980-9c4d-11eb-9f4a-f2756eb073ca.png)
And the 2.0 solution:
![image](https://user-images.githubusercontent.com/22027681/114589534-61134600-9c4d-11eb-9fca-df9f0954bf93.png)

**Comment by manuelap-msft** [comment]
Sorry, my bad! We renamed this flow from RPA to Desktop flow so it's called Admin | Sync Template v3 (Desktop flows) and it looks like you have that. 

If you still have an Admin | Sync Template v2 (RPA) flow in you solution you can safely delete that, and then click on the ... next to the 2.0 solution and select "Apply upgrade" which should then succeed.

**Comment by jefmeyer** [comment]
No problem, thanks for the clarification.  So my original issue is that when I attempted to upgrade Core 1.89 to 2.0, the upgrade failed and installed 2.0 in parallel.  Meaning now I have 1.89 and 2.0 installed.  Can we simply delete the 1.89 solution?
![image](https://user-images.githubusercontent.com/22027681/114590702-b7cd4f80-9c4e-11eb-8c05-9b32e54480f9.png)

**Comment by manuelap-msft** [comment]
You won't be able to delete 1.89 due to the dependencies - deleting the solution will also remove all the tables and the data in the tables, so we would not recommend that.

If you click on the ... next to the solution you should be able to select "Apply Upgrade" after you have removed the troublesome v2 flow. 

Now that I think of it, I'm not sure if the Apply Upgrade will show up if you click the ... on 1.89 or on 2.0 - but it will be on one of them!

**Comment by jefmeyer** [comment]
I don't see a V2 of the flow to delete, so not sure how to proceed with cleanup.  The Apply Upgrade is still failing with the following error.  We only see Apply Upgrade on the 1.89 solution, which makes sense.  Any other ideas? :)

Solution dependencies exist, cannot uninstall. DependencyCount : 1 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_409c1, Id: 696e81c1-a969-4e22-bfef-2887b81f54c8, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Sync Template v2 (RPA), Id: 86f47022-b7f1-ea11-a815-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

**Comment by JeneferM-MSFT** [comment]
You have definitely hit some kind of product bug from upgrade. But lets see if we can get you out of it.
If you go the Power BI that comes with the toolkit you should be able to track down this lost flow. There may be an easier way but this is what is coming to mind.

If you go to the Cloud Flows tab and in the Display Name, look for this errant flow
![image](https://user-images.githubusercontent.com/62659043/114631194-638b9500-9c79-11eb-91d0-1d9e311cc05e.png)

It should then filter the environments so that only the environment with this flow shows
![image](https://user-images.githubusercontent.com/62659043/114631307-92097000-9c79-11eb-80fa-9672fc056517.png)

Then in the Set Flow Permissions App (part of Core), you can select that environment and that app, give yourself permissions to it and then delete it
![image](https://user-images.githubusercontent.com/62659043/114631460-d98ffc00-9c79-11eb-918a-3d3f69182edc.png)

**Comment by jefmeyer** [comment]
So unfortunately, we're not seeing it in the Power BI reports.  We did take the ID value from the upgrade error and attempted to open that flow, but received a response that the flow has been deleted.  We haven't deleted this flow and curious to know if it's part of the upgrade process.
![image](https://user-images.githubusercontent.com/22027681/114720345-90818b80-9cfd-11eb-89f5-cc3d70697d27.png)
 
 Should we try to upgrade the 1.89 solution to an earlier version prior to 2.0 to see if that resolves the issue?  Alternatively, do you know of any other tricks to clear out this flow reference?  It seems like the flow is orphaned somewhere in our tenant.

**Comment by manuelap-msft** [comment]
Hello,

this is very bizarre! Well, we didn't delete - but we renamed the flow from Admin | Sync Template v2 (RPA) to Admin | Sync Template v3 (Desktop flows). So the same flow still exists but has been renamed as part the previous upgrade (1.89).

It sounds like there are some gremlins in the background hanging on the to v2 name of this flow. We have had this issue once before with a customer, where everything looked fine on the Flow side but it turned out that the LogicApps related to the flow in the background hadn't been deleted properly. This was a product bug, and through raising a support ticket, a support engineer could run a clean-up and get the solution back in a healthy state.

I would recommend you raise a support ticket, and mention especially the last screenshot where you get the "Flow has been deleted" message. I think they can run some scripts in the background to clean up the references - from what I remember last time this wasn't anything you (a customer) could fix themselves, but some wires crossing on our side in the background.

Sorry we couldn't help you here further!
Manuela

**Comment by jefmeyer** [comment]
Thank you so much for the assistance, we'll get a ticket open and hopefully be back up again soon.  Take care!

**Comment by jefmeyer** [comment]
So unfortunately, MSFT support isn't able to find the flow on their end.  Would it make sense to try upgrading from 1.89 to a version earlier than 2.0 first to see if this resolves our issue?  Sadly, I fear that we'll need to start from scratch with the CoE and looking for any last ditch efforts to recover from this error.

**Comment by JeneferM-MSFT** [comment]
There were some generalized issues seen around upgrade last week. I dont think using an interum will help but you might be able to just try regular upgrade again to see if works today now that those issues are resolved. 

I suggest trying
1) Upgrade using the current upgrade path, ensuring unmanaged layers are removed:  [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
1) Try upgrading using the "Switch to Classic" and overwrite technique for upgrade instead to the latest Core

Hope it works!

**Comment by JeneferM-MSFT** [comment]
See my comment from 10/30/2020 in this issue for how to upgrade using Switch to Classic [https://github.com/microsoft/powerapps-tools/issues/550](https://github.com/microsoft/powerapps-tools/issues/550)

**Comment by JeneferM-MSFT** [comment]
I'm going to close this since there isn't anything we can do further to assist. Thanks for using CoE
