### ISSUE TITLE
Environment not getting deleted using CoE

### ISSUE THREAD

**Issue by abhishekmaru** [microsoft/powerapps-tools#933]
Hi, I have deleted one Environment from CoE Power Platform Admin view however it doesn't get deleted from Power Platform admin center. It been 3 days I performed this activity.

Also for one environment, in the audit tab inside field "Admin - Microsoft Teams Environment Status" marked it as "Rejected"...3 days ago but still environment is not deleted.

Any suggestions.

**Comment by JeneferM-MSFT** [comment]
Hello. Sounds like we have two questions

1) Deleted an environment from the tenant but it still shows in inventory after 3 days
We check for deleted objects using this flow: **_CLEANUP - Admin | Sync Template v3 (Check Deleted)_**
It is set to run once every 2 weeks by default due to how long running it is, you can trigger it to run now if you'd like it to get the values sooner. 

2) Marked a Teams environment as Rejected, still there after 3 days
We check for Teams environment state using this flow: **_Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments_**
It is set to run once a week, and will only pick up environments at lest 1 week old. 

Hope that helps

**Comment by abhishekmaru** [comment]
Hi, Thank you for feedback. Here are the observation.
1. For the first issue, I have activated the flow - **CLEANUP - Admin | Sync Template v3 (Check Deleted)**
2. For issue second, I could not find this flow **Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments** in the **Center of Excellence - Core Components** solution.

Could you please suggest do I need to check this workflow under different tab, I have latest version of CoE toolkit installed on my tenant.

**Comment by manuelap-msft** [comment]
Hello,

1. Can you clarify if you mean: You deleted an environment from the Power Platform Admin View in the CoE Core Components (model driven app) and expected it to delete in the Power Platform Admin Center or the other way round?
2. This flow is part of the Center of Excellence - Governance Components solution.
Thank you
Manuela

**Comment by abhishekmaru** [comment]
Hi,

1. Can you clarify if you mean: Yes, I deleted an environment from the Power Platform Admin View in the CoE Core Components and expected it to be deleted from Power Platform admin center.
2. Governance Component - Thank you...let me install the Governance component of Coe toolkit.

**Comment by manuelap-msft** [comment]
I think there may be a misunderstanding here - you can't delete environments, or any other resources, from the Power Platform Admin View.

In the background, the CoE has flows that write meta-data information about your resources (such as environment name, owner, when it was created,...) into Dataverse tables and the Power Platform Admin View is linked to the rows in that table, but not to the actual environment. So when you deleted something from the Power Platform Admin View, you only deleted a row in a table.

I'm closing the issue as I hope it resolved your questions.

Thanks for using the CoE,
Manuela
