### ISSUE TITLE
[PRODUCT BUG]: CLEANUP - Admin | Sync Template v3 (Connection Status) Failed with JSON format

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#937]
CLEANUP - Admin | Sync Template v3 (Connection Status) is failing due to an error

ERROR : The response is not in a JSON format.
![image](https://user-images.githubusercontent.com/78148795/115144648-6caaa680-a06b-11eb-8b8d-7496607fc158.png)

Kindly help to fix this issue

**Comment by JeneferM-MSFT** [comment]
Hello we have seen other people get this error and it is a product bug for which you will need to seen help from support. 

Basically sometimes the product holds onto deleted apps in some way such that calls to **_Get Apps as Admin_** returns the deleted app, but then calls to **Get App as Admin** fails (as would be expected)

We suggest that you create a flow like the below, or use this one attached.
[ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip](https://github.com/microsoft/powerapps-tools/files/6331385/ProductBug-GetAppfails-TheresponseisnotinaJSONformat_20210418134636.zip)

Select the environment which repro for you here, it loops the apps, will hit the same failure and the you can go to support with that flow since this is not an issue with the toolkit. 
![image](https://user-images.githubusercontent.com/62659043/115147736-b5d20a80-a019-11eb-98e1-eb80950b2747.png)

**Comment by JeneferM-MSFT** [comment]
Closing out as there is no action for the toolkit
