### ISSUE TITLE
[BUG]: Spelling issue within Innovation Backlog App

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#947]
**Describe the bug**
Spelling issue within Innovation Backlog App

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Innovation Backlog
 - Version 1.20
 - Innovation Backlog

**To Reproduce**
1. Log into Innovation Backlog app
2. Create an item
3. Go to Workflow stage
4. Select Do you have a workflow process map? = No
5. Spelling error "interst"

**Expected behavior**
Should be interest.

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/115434943-356dfe00-a201-11eb-89e5-1d82c82d1f9d.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello I fixed this in the local copy but will not re-ship just for this, so not holding this issue open. 
Thank you for helping make CoE great.

**Comment by JeneferM-MSFT** [comment]
Actually just caught a bug in the tool that the "New Tool" page had its height off. Fixed that too so will go ahead and hold open to remember to reship, with your spelling fixed too.

**Comment by JeneferM-MSFT** [comment]
Hello. We have just released the May edition of the toolkit and it contains this fix. 
Please be sure to follow the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in order to remove any unmanaged layers you have in place, or you will not receive the update. 

Thank you for helping make CoE great!
