### ISSUE TITLE
CoE kit core components Flows not fetching data

### ISSUE THREAD

**Issue by LakshmanChand** [microsoft/powerapps-tools#948]
Hi,
 I am using 1.39 version of Core Components.  All the Admin Sync Template flows were running fine till January. The flows are now not fetching the data and i could see there is a big difference in the data. I have observed few flows (example Admin sync template V2 (Apps) running very long time. I am using this data to report new users every month and new apps every month. The report shows there are no new users in the month of February, March and April and very less new apps in February March and April.

Is there an option to do a full load of all the tables

**Comment by manuelap-msft** [comment]
Hello,

you are on a very old version of the Core Components - our current version is 2.x - we have made many performance improvements, bug fixes and optimizations since the version you're on. Unfortunately we are unable to support versions this far back, and you will have to upgrade before we can assist you.

Please see here for the upgrade process:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by LakshmanChand** [comment]
Hi Manuela,

Before upgrading my production environment, I took a backup of my current environment and restored on a sandbox environment. i upgraded the Core components to version 1.78. After upgrading, i have followed the instructions as mentioned in the below link. The flow CLEANUP - Admin | Sync Template v3 (Check Deleted) ran for 21 days and after turning on the other flows, i did not see they are triggering. Can you please advise
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows

**Comment by JeneferM-MSFT** [comment]
Hello. Version 1.78 is also quite old. The current version of Core is [2.0.10](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_2_0_10_managed.zip). You will need to be on that version and then if you have still have issues please post them. 

Note also that in order to install updates you need to remove unmanaged layers from all the flows as shown in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by LakshmanChand** [comment]
I have updated my solution to 2.0.10. The flow Admin | Sync Template v3 (Apps) is still not triggering. I changed the connection from CDS (current environment ) CoE Connection to CoE v3 sync Templates (current) and then i am getting below error.
There's a problem that needs to be fixed to trigger this flow. To see more details, open Flow checker. Last successful trigger: 2:21 AM 04/21/2021 and "More than one concurrent Delete requests detected for an Entity 52b03dbe-c5a2-eb11-b1ac-000d3a2ada09 and ObjectTypeCode 301."

My observations:
I have two environments with CoE kit. Would this enable two trigger monitors at CDS entity and cause the issue with concurrent delete request error? I have turn off the flows on one of the CoE kit. I am still getting the same error. 
More than one concurrent Delete requests detected for an Entity 52b03dbe-c5a2-eb11-b1ac-000d3a2ada09 and ObjectTypeCode 301.
