### ISSUE TITLE
App not displaying correctly on wider monitors

### ISSUE THREAD

**Issue by samhegartyunsw** [microsoft/powerapps-tools#95]
**Describe the bug**
On a 1920 x 1080 resolution, the menu items don't display the associated text. Making the browser window slightly smaller makes it appear correctly. This is on V2 on the crisis communication app.

![image](https://user-images.githubusercontent.com/62010356/76296593-7ca17400-630a-11ea-9c6b-ccc2a7d3c9dd.png)

**Comment by mr-dang-msft** [comment]
Acknowledged. We're working on improving the responsiveness of the home menu. 
I'll report back when we update it with such a fix 👍

**Comment by mr-dang-msft** [comment]
I have redone the menu on the home page with more support for wider screens. 

- The image now has a maximum height/width so it doesn't occupy the template as much
- The screen name has fewer conditions in which it is hidden (only when the template is so small that text would not fit)
- The gallery will wrap if there is enough height to accommodate more tiles.

Link: https://github.com/microsoft/powerapps-tools/commit/b48c746ee5d96884efc5ec6654a696dac6c2b8de#diff-b31cdce1a7fc4de5376d4341db3de27b

Please keep this open if you have further suggestions on the responsiveness of any screen.

**Comment by Merel84** [comment]
For me this issue is still not resolved. When I deploy to Teams, I can't click on any of the links unless I make the screen small.

![image](https://user-images.githubusercontent.com/62138010/76624218-2d8b5700-6535-11ea-8819-0117a4b87228.png)

Same occurs in browser... How could I solve this? Thanks!

**Comment by Merel84** [comment]
In addition, and apologies for the perhaps n00b question, but if I've already shared the app but need to use the new package, would I have to delete the 'old' app and then use the new package?

**Comment by mr-dang-msft** [comment]
Hi @Merel84 ,
1. I think you may have accidentally readjusted the Y property of the HomeMenu component (the grey menu at the bottom).
- To fix: Change the Y property so that it rests below the top component:
`HomeComponent_1.Y+HomeComponent_1.Height`
This means "Make the HomeMenu sit below where the HomeComponent starts plus its height."

2. You can import the latest CrisisCommunication.zip file on top of the existing app. 
- In the import step you originally did, instead of "Create as new" you can click that and change it to 
"Update". 
- In that case, it will pull up a list of the apps in the environment. Make sure you choose the right one you to overwrite.
![image](https://user-images.githubusercontent.com/39354102/76682025-ab8f4280-65b5-11ea-9049-411a4e53632e.png)
- Note you will need to open the newly imported app to remove the SharePoint connections and add your own again.
- File > Save > Publish to show the latest version.
- Apps have a version history. At any time you can go to the versions of the app and roll it back if you want to as well.
![image](https://user-images.githubusercontent.com/39354102/76682084-22c4d680-65b6-11ea-9b86-6bf4c255c942.png)

Let me know if you need elaboration on any of these steps.

**Comment by Merel84** [comment]
Hi @mr-dang-msft , thank you so much, this worked perfectly! Have a great weekend!
