### ISSUE TITLE
[BUG]: Copy components of CoE Starter Kit into an unmanaged solution

### ISSUE THREAD

**Issue by leozak06** [microsoft/powerapps-tools#96]
**Describe the bug**
I am trying to make a copy of all the components in the CoE Starter kit and put them in an unmanaged solution. I have been able to copy apps and flows into the unmanaged solution, but am unable to copy entities, web resources, environment variables, option sets, etc. Is there any way I can do that? If I just add existing, the elements are still installed as part of a managed solution so it restricts me from making any modifications. 

Once I am able to do that, I want to be able to make modifications to the components and then export as a managed solution. 

**Interface(please complete the following information):**
 - Browser - Microsoft Edge

**Comment by manuelap-msft** [comment]
All entities in the CoE Kit allow customization:
![image](https://user-images.githubusercontent.com/55705669/76409620-8b2d7100-6386-11ea-9800-d4c9ddc2126a.png)

You will be able to edit the display name and add new fields, and new forms and views based on an entity. You can also modify the model driven app.

Some components can't be modified due to their dependency, e.g. you can not remove a field from an entity, but you can choose to not make it required anymore and not show it on the form or view.

 Please refer to the docs for how to work with solutions 
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/solutions-overview
