### ISSUE TITLE
Admin | Welcome Email is not working

### ISSUE THREAD

**Issue by krishnaVSU2020** [microsoft/powerapps-tools#960]
Hi Team,

I see the below issue when I turn on the **Admin | Welcome Email** Flow in D4T COE.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core compoenets]
 - Version [e.g. 1.9]

**To Reproduce**
1. Go to Teams
2. Navigate to the D4T environment where you installed COE
3. Click **Admin | Welcome Email** Flow
4. Turn on the Flow
5. I see the below error:
![image](https://user-images.githubusercontent.com/70860420/115977116-eac2ed80-a542-11eb-889c-b4a451953795.png)

**Expected behavior**
The Flow should get activate without any issues as it is my own environment

**Comment by manuelap-msft** [comment]
Hello,

thank you for letting us know - this flow is still using the legacy Dataverse connector which seems to not work in Dataverse for Teams. We have this fixed for the next release, which will go out first week of May.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Hello. We have just released the May edition of the toolkit and it contains this fix. 
Please be sure to follow the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in order to remove any unmanaged layers you have in place, or you will not receive the update. 

Thank you for helping make CoE great!
