### ISSUE TITLE
[BUG]: Not able to import the COE Starter Kit core solution into a Dataverse for Teams environment

### ISSUE THREAD

**Issue by HelmutWimmer** [microsoft/powerapps-tools#973]
**Describe the bug**
Import of solution CenterofExcellenceCoreComponentsTeams_1_9_managed.zip not possible

**Component (please tell us which flow or app you are experiencing issues with):**
 - Coere
 - Version 1.9
 - All Canvas Apps fail while trying to import

**To Reproduce**
1. Go to a Dataverse for Teams team in MS Teams
2. Click on PowerApps, Build, See All
3. Click on Import, select file, create all necessary connectors and set env. variables

**Expected behavior**
Solution should be imported without failure.

Downloaded log:
[CenterofExcellenceCoreComponentsTeams_1_9_managed.zip_import.txt](https://github.com/microsoft/powerapps-tools/files/6392194/CenterofExcellenceCoreComponentsTeams_1_9_managed.zip_import.txt)

**Additional context**
Tried it in 3 different O365 tenants, and a variety of Dataverse for Teams environments, always fails.
Same error as reported here https://github.com/microsoft/powerapps-tools/issues/922

**Comment by JeneferM-MSFT** [comment]
Unfortunately per Manuela, we had to point the user from 922 to support: 

```
Hello,

please raise a support ticket via your usual support channels. We have many customers who have successfully installed the released version in Teams, so unfortunately you may be experiencing a product bug here. It might be worth trying the import again as it may have just been a temporary issue.

In your xml file, if you parse through it the error message is the below, which is nothing to do with the CoE kit itself:
CanvasApp import: FAILURE: Code: GraphUserDetailNotFound Message: The user '00000000-0000-0000-0000-000000000000' was not found in Graph


```

**Comment by HelmutWimmer** [comment]
Well obviously this affects more people, so unhappy to see this not being resolved by you.

**Comment by manuelap-msft** [comment]
Jenefer and myself are only able to support the CoE Starter Kit solution, and bugs, issues and questions related to it. Looking at your error log file, the error states "CanvasApp import: FAILURE: Code: GraphUserDetailNotFound Message: The user '00000000-0000-0000-0000-000000000000' was not found in Graph." which is not an error message related to the CoE Starter Kit but instead a product issue. Jenefer and myself are not Support Engineers, nor are we able to support the Power Platform / Dataverse for Teams products. Hence, we ask that you raise this through regular support channels. We have many customers successfully installing the kit in Teams environments therefore do not believe that this issue is related to the CoE Starter Kit solution.

Thank you for your comment,
Manuela
