### ISSUE TITLE
CoE Starter Kit - Archive Request Notifications Not Being Sent

### ISSUE THREAD

**Issue by drace3000** [microsoft/powerapps-tools#993]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
1. Admin | Archive and Clean Up V2 (Start Approval for Apps)
2. Admin | Archive and Clean Up V2 (Start Approval for Flows)

 - SOLUTION [Governance Components]

 - App or Flow QUALIFICATION
     Checks for apps/flows that haven't been modified or launched in the last day and notifies the app owner whether the app can be deleted.
 -This flow starts the approval process and writes the approval task to the Archive Approval Dataverse table with a request notification (see attached copy of notification.

**To Reproduce**
1. Went to the CoE tables and modified the last modified or launched dates to force flow to find qualified apps or flows. Also changed this interval directly in the flow
2. Run the flows on May 4. 2021

**Expected behavior**
Notification sent to App / Flow owner (see attached files for expected notification per CoE documentation)
Note that CoE does send out notfications for other CoE apps / flows so we know notifications are working

**Screenshots**
![Notification Message](https://user-images.githubusercontent.com/22414379/116995536-2e86c700-aca8-11eb-9422-91d22ab179b5.JPG)
![Item2 Data Validation](https://user-images.githubusercontent.com/22414379/116995602-42cac400-aca8-11eb-925b-7bbcced2ed87.JPG)
![Item2 Data Validation Flows](https://user-images.githubusercontent.com/22414379/116995612-465e4b00-aca8-11eb-972b-1794bd2f14b4.JPG)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid I cannot really help you with the information provided above. 

Can you please tell me what version of the Governance solution are you using? 

Then also please do the following:
1. Go to the run of **_Start Approval for Apps_** where you expected the approval to be created
2. Go to the **_List apps not launched or marked modified since Past Time_** action, and open the outputs. Is the app you expected listed in there? 
![image](https://user-images.githubusercontent.com/62659043/117013177-dbfbd980-acac-11eb-881e-64b216b11d97.png)
3. If so, note the number it is returned and go to the **_Create Archival Request for Each_** loop and find it 
![image](https://user-images.githubusercontent.com/62659043/117013395-11a0c280-acad-11eb-9717-862bdf4df7ff.png)
4. Return showing what path it followed in the loop

**Comment by manuelap-msft** [comment]
Closing issues where no follow up was provided.
